apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: edgecloud-high
value: 1000000
globalDefault: false
description: "High priority class for Edge-Cloud Orchestrator core services."
