apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "edgecloud.labels" . | nindent 4 }}
    name: edgecloud
    environment: {{ .Values.global.environment | default "production" }}
