apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edgecloud-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SumitMahajan01/edge-cloud-orchestrator.git
    targetRevision: main
    path: infra/k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: edgecloud-prod
  syncPolicy:
    # Manual sync for production as a safety gate
    # Workflow in cd.yml will trigger the sync via ArgoCD CLI/API
    automated: null
    syncOptions:
      - CreateNamespace=true
