apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployments/api.yaml
  - deployments/api-gateway.yaml
  - deployments/scheduler-service.yaml
  - deployments/task-service.yaml
  - deployments/node-service.yaml
  - deployments/websocket-gateway.yaml
  - deployments/agent.yaml
  - deployments/metrics-service.yaml
  - services/internal-services.yaml
  - services/api-gateway.yaml
  - hpa/autoscalers.yaml
  - pdb/disruption-budgets.yaml

configMapGenerator:
  - name: app-config
    envs:
      - configmaps/app.env

commonLabels:
  app.kubernetes.io/part-of: edgecloud
