apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: edgecloud-default-policy

spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: edgecloud
  egress:
    - to:
        - namespaceSelector: {}
