// This file is auto-generated by @hey-api/openapi-ts

import type { GetV2NodesByIdResponse, GetV2NodesResponse, GetV2TasksByIdResponse, GetV2TasksResponse, PostV2AgentsCertificatesSignResponse, PostV2AuthLoginResponse, PostV2AuthRegisterResponse, PostV2NodesResponse, PostV2TasksResponse } from './types.gen.js';

export const postV2AgentsCertificatesSignResponseTransformer = async (data: any): Promise<PostV2AgentsCertificatesSignResponse> => {
    if (data.expiresAt) {
        data.expiresAt = new Date(data.expiresAt);
    }
    return data;
};

export const postV2AuthLoginResponseTransformer = async (data: any): Promise<PostV2AuthLoginResponse> => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const postV2AuthRegisterResponseTransformer = async (data: any): Promise<PostV2AuthRegisterResponse> => {
    data.expiresAt = new Date(data.expiresAt);
    return data;
};

export const getV2NodesResponseTransformer = async (data: any): Promise<GetV2NodesResponse> => {
    if (data.data) {
        data.data = data.data.map((item: any) => {
            item.lastHeartbeat = new Date(item.lastHeartbeat);
            return item;
        });
    }
    return data;
};

export const postV2NodesResponseTransformer = async (data: any): Promise<PostV2NodesResponse> => {
    data.lastHeartbeat = new Date(data.lastHeartbeat);
    return data;
};

export const getV2NodesByIdResponseTransformer = async (data: any): Promise<GetV2NodesByIdResponse> => {
    data.lastHeartbeat = new Date(data.lastHeartbeat);
    return data;
};

export const getV2TasksResponseTransformer = async (data: any): Promise<GetV2TasksResponse> => {
    if (data.data) {
        data.data = data.data.map((item: any) => {
            item.submittedAt = new Date(item.submittedAt);
            return item;
        });
    }
    return data;
};

export const postV2TasksResponseTransformer = async (data: any): Promise<PostV2TasksResponse> => {
    data.submittedAt = new Date(data.submittedAt);
    return data;
};

export const getV2TasksByIdResponseTransformer = async (data: any): Promise<GetV2TasksByIdResponse> => {
    data.submittedAt = new Date(data.submittedAt);
    return data;
};
