// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ErrorSchema
 */
export type Def0 = {
    error: {
        /**
         * Machine-readable error code
         */
        code: string;
        /**
         * Optional error details
         */
        details?: unknown;
        /**
         * Human-readable error description
         */
        message: string;
        /**
         * Unique request ID
         */
        requestId?: string;
        /**
         * Error stack trace (non-production only)
         */
        stack?: string;
        /**
         * ISO 8601 timestamp
         */
        timestamp?: Date;
    };
};

/**
 * HealthSchema
 */
export type Def1 = {
    checks?: {
        [key: string]: boolean;
    };
    service: string;
    status: 'degraded' | 'healthy' | 'unhealthy';
    timestamp: Date;
    version?: string;
};

export type GetV2AdminAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        userId?: string;
        action?: string;
        limit?: number;
    };
    url: '/v2/admin/audit-logs';
};

export type GetV2AdminAuditLogsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminCleanupData = {
    body: {
        olderThanDays: number;
        types: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v2/admin/cleanup';
};

export type PostV2AdminCleanupResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AdminDlqEventsData = {
    body?: never;
    path?: never;
    query?: {
        topic?: string;
        status?: 'PENDING' | 'PERMANENTLY_FAILED' | 'REPROCESSED' | 'RETRYING';
        limit?: number;
        offset?: number;
    };
    url: '/v2/admin/dlq/events';
};

export type GetV2AdminDlqEventsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminDlqEventsByIdRetryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/admin/dlq/events/{id}/retry';
};

export type PostV2AdminDlqEventsByIdRetryResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminDlqPurgeData = {
    body?: {
        olderThanDays?: number;
    };
    path?: never;
    query?: never;
    url: '/v2/admin/dlq/purge';
};

export type PostV2AdminDlqPurgeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AdminDlqStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/admin/dlq/stats';
};

export type GetV2AdminDlqStatsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminEventsRepublishData = {
    body: {
        entityId: string;
        eventType: string;
        targetTopic?: string;
    };
    path?: never;
    query?: never;
    url: '/v2/admin/events/republish';
};

export type PostV2AdminEventsRepublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminEventsRepublishRangeData = {
    body: {
        dryRun?: boolean;
        eventType: string;
        fromTimestamp: string;
        toTimestamp: string;
    };
    path?: never;
    query?: never;
    url: '/v2/admin/events/republish-range';
};

export type PostV2AdminEventsRepublishRangeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AdminHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/admin/health';
};

export type GetV2AdminHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminMlRetrainData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/admin/ml/retrain';
};

export type PostV2AdminMlRetrainResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AdminUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/admin/users';
};

export type GetV2AdminUsersResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AdminUsersByIdDeactivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/admin/users/{id}/deactivate';
};

export type PostV2AdminUsersByIdDeactivateResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV2AdminUsersByIdRoleData = {
    body: {
        role: 'ADMIN' | 'OPERATOR' | 'SUPER_ADMIN' | 'VIEWER';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/admin/users/{id}/role';
};

export type PatchV2AdminUsersByIdRoleResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AdminWsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/admin/ws-stats';
};

export type GetV2AdminWsStatsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AgentsCaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/agents/ca';
};

export type GetV2AgentsCaResponses = {
    /**
     * Default Response
     */
    200: {
        certificate?: string;
    };
};

export type GetV2AgentsCaResponse = GetV2AgentsCaResponses[keyof GetV2AgentsCaResponses];

export type PostV2AgentsCertificatesSignData = {
    body: {
        /**
         * One-time bootstrap token
         */
        bootstrapToken: string;
        cpuCores?: number;
        /**
         * PEM encoded Certificate Signing Request
         */
        csr: string;
        hardwareId?: string;
        ipAddress?: string;
        memoryGB?: number;
        nodeName: string;
        port?: number;
        region: string;
        storageGB?: number;
    };
    path?: never;
    query?: never;
    url: '/v2/agents/certificates/sign';
};

export type PostV2AgentsCertificatesSignErrors = {
    /**
     * Default Response
     */
    400: Def0;
    /**
     * Default Response
     */
    401: Def0;
    /**
     * Default Response
     */
    403: Def0;
};

export type PostV2AgentsCertificatesSignError = PostV2AgentsCertificatesSignErrors[keyof PostV2AgentsCertificatesSignErrors];

export type PostV2AgentsCertificatesSignResponses = {
    /**
     * Default Response
     */
    200: {
        caCertificate?: string;
        certificate?: string;
        expiresAt?: Date;
        nodeId?: string;
    };
};

export type PostV2AgentsCertificatesSignResponse = PostV2AgentsCertificatesSignResponses[keyof PostV2AgentsCertificatesSignResponses];

export type PostV2AgentsHeartbeatData = {
    body?: {
        metrics?: {
            cpu_usage?: number;
            memory_usage?: number;
        };
        status?: string;
        timestamp?: number;
    };
    path?: never;
    query?: never;
    url: '/v2/agents/heartbeat';
};

export type PostV2AgentsHeartbeatResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AgentsTasksPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/agents/tasks/pending';
};

export type GetV2AgentsTasksPendingErrors = {
    /**
     * Default Response
     */
    404: Def0;
};

export type GetV2AgentsTasksPendingError = GetV2AgentsTasksPendingErrors[keyof GetV2AgentsTasksPendingErrors];

export type GetV2AgentsTasksPendingResponses = {
    /**
     * Default Response
     */
    200: {
        cpu_fuel?: number | null;
        image?: string;
        input?: {
            [key: string]: unknown;
        };
        memory_limit_mb?: number;
        runtime?: string;
        task_id?: string;
        timeout_seconds?: number;
        wasm_artifact_id?: string | null;
    };
};

export type GetV2AgentsTasksPendingResponse = GetV2AgentsTasksPendingResponses[keyof GetV2AgentsTasksPendingResponses];

export type PostV2AgentsTasksByTaskIdResultData = {
    body: {
        duration_ms?: number;
        error?: string | null;
        exit_code: number;
        metrics?: {
            cpu_usage_avg?: number;
            memory_usage_max?: number;
            network_egress_bytes?: number;
            network_ingress_bytes?: number;
        };
        status: string;
        stderr?: string;
        stdout?: string;
    };
    path: {
        taskId: string;
    };
    query?: never;
    url: '/v2/agents/tasks/{taskId}/result';
};

export type PostV2AgentsTasksByTaskIdResultResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AgentsTasksByTaskIdStatusData = {
    body: {
        status: string;
    };
    path: {
        taskId: string;
    };
    query?: never;
    url: '/v2/agents/tasks/{taskId}/status';
};

export type PostV2AgentsTasksByTaskIdStatusResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AlertsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/alerts/';
};

export type GetV2AlertsResponses = {
    /**
     * Default Response
     */
    200: {
        alerts?: Array<{
            acknowledgedAt?: string | null;
            description?: string;
            firedAt?: string;
            id?: string;
            resolvedAt?: string | null;
            severity?: 'CRITICAL' | 'HIGH' | 'LOW' | 'MEDIUM';
            source?: string;
            title?: string;
        }>;
    };
};

export type GetV2AlertsResponse = GetV2AlertsResponses[keyof GetV2AlertsResponses];

export type PostV2AlertsTestData = {
    body: {
        description: string;
        severity: 'CRITICAL' | 'HIGH' | 'LOW' | 'MEDIUM';
        title: string;
    };
    path?: never;
    query?: never;
    url: '/v2/alerts/test';
};

export type PostV2AlertsTestResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AlertsByIdAcknowledgeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/alerts/{id}/acknowledge';
};

export type PostV2AlertsByIdAcknowledgeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AnalyticsCostData = {
    body?: never;
    path?: never;
    query?: {
        from?: Date;
        to?: Date;
        nodeId?: string;
    };
    url: '/v2/analytics/cost';
};

export type GetV2AnalyticsCostResponses = {
    /**
     * Default Response
     */
    200: {
        costByNode?: Array<{
            cost?: number;
            nodeId?: string;
            nodeName?: string;
            taskCount?: number;
        }>;
        costOverTime?: Array<{
            cost?: number;
            date?: string;
        }>;
        totalActualCost?: number;
        totalSavings?: number;
    };
};

export type GetV2AnalyticsCostResponse = GetV2AnalyticsCostResponses[keyof GetV2AnalyticsCostResponses];

export type GetV2ApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/api-keys/';
};

export type GetV2ApiKeysResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2ApiKeysData = {
    body: {
        expiresAt?: unknown | Date | unknown;
        name: string;
        permissions?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/v2/api-keys/';
};

export type PostV2ApiKeysResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV2ApiKeysByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/api-keys/{id}';
};

export type DeleteV2ApiKeysByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/v2/auth/login';
};

export type PostV2AuthLoginErrors = {
    /**
     * Default Response
     */
    401: Def0;
    /**
     * Default Response
     */
    429: Def0;
};

export type PostV2AuthLoginError = PostV2AuthLoginErrors[keyof PostV2AuthLoginErrors];

export type PostV2AuthLoginResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        expiresAt: Date;
        refreshToken: string;
        token: string;
        user: {
            email: string;
            id: string;
            name?: unknown | string | unknown;
            role: string;
        };
    };
};

export type PostV2AuthLoginResponse = PostV2AuthLoginResponses[keyof PostV2AuthLoginResponses];

export type PostV2AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/auth/logout';
};

export type PostV2AuthLogoutResponses = {
    /**
     * Default Response
     */
    200: {
        success?: boolean;
    };
};

export type PostV2AuthLogoutResponse = PostV2AuthLogoutResponses[keyof PostV2AuthLogoutResponses];

export type GetV2AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/auth/me';
};

export type GetV2AuthMeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AuthRefreshData = {
    body: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/v2/auth/refresh';
};

export type PostV2AuthRefreshResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2AuthRegisterData = {
    body: {
        email: string;
        name: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/v2/auth/register';
};

export type PostV2AuthRegisterErrors = {
    /**
     * Default Response
     */
    400: Def0;
    /**
     * Default Response
     */
    409: Def0;
};

export type PostV2AuthRegisterError = PostV2AuthRegisterErrors[keyof PostV2AuthRegisterErrors];

export type PostV2AuthRegisterResponses = {
    /**
     * Default Response
     */
    201: {
        accessToken: string;
        expiresAt: Date;
        refreshToken: string;
        token: string;
        user: {
            email: string;
            id: string;
            name?: unknown | string | unknown;
            role: string;
        };
    };
};

export type PostV2AuthRegisterResponse = PostV2AuthRegisterResponses[keyof PostV2AuthRegisterResponses];

export type DeleteV2AuthSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/auth/sessions';
};

export type DeleteV2AuthSessionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2AuthSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/auth/sessions';
};

export type GetV2AuthSessionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV2AuthSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/auth/sessions/{id}';
};

export type DeleteV2AuthSessionsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2CarbonByRegionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/carbon/by-region';
};

export type GetV2CarbonByRegionResponses = {
    /**
     * Default Response
     */
    200: Array<{
        carbonIntensityGco2?: number;
        lastUpdatedAt?: string;
        source?: string;
        zone?: string;
    }>;
};

export type GetV2CarbonByRegionResponse = GetV2CarbonByRegionResponses[keyof GetV2CarbonByRegionResponses];

export type GetV2CarbonIntensityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/carbon/intensity';
};

export type GetV2CarbonIntensityResponses = {
    /**
     * Default Response
     */
    200: {
        regions?: Array<{
            carbonIntensityGco2?: number;
            lastUpdatedAt?: string;
            source?: string;
            zone?: string;
        }>;
    };
};

export type GetV2CarbonIntensityResponse = GetV2CarbonIntensityResponses[keyof GetV2CarbonIntensityResponses];

export type GetV2CarbonPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/carbon/policy';
};

export type GetV2CarbonPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        activePolicy?: string;
        carbonWeight?: number;
        isActive?: boolean;
    };
};

export type GetV2CarbonPolicyResponse = GetV2CarbonPolicyResponses[keyof GetV2CarbonPolicyResponses];

export type PatchV2CarbonPolicyData = {
    body: {
        carbonWeight: number;
    };
    path?: never;
    query?: never;
    url: '/v2/carbon/policy';
};

export type PatchV2CarbonPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        carbonWeight?: number;
        success?: boolean;
    };
};

export type PatchV2CarbonPolicyResponse = PatchV2CarbonPolicyResponses[keyof PatchV2CarbonPolicyResponses];

export type GetV2CarbonReportData = {
    body?: never;
    path?: never;
    query?: {
        from?: Date;
        to?: Date;
        tenantId?: string;
        format?: 'csv' | 'json';
    };
    url: '/v2/carbon/report';
};

export type GetV2CarbonReportResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2CarbonSavingsData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/v2/carbon/savings';
};

export type GetV2CarbonSavingsResponses = {
    /**
     * Default Response
     */
    200: {
        equivalentTreesPlanted?: number;
        savingsHistory?: Array<{
            date?: string;
            savedGco2?: number;
        }>;
        totalSavedGco2Today?: number;
        totalSavedGco2Week?: number;
    };
};

export type GetV2CarbonSavingsResponse = GetV2CarbonSavingsResponses[keyof GetV2CarbonSavingsResponses];

export type GetV2CarbonSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/carbon/summary';
};

export type GetV2CarbonSummaryResponses = {
    /**
     * Default Response
     */
    200: {
        equivalentTreesPlanted?: number;
        totalSavedGco2Today?: number;
        totalSavedGco2Week?: number;
    };
};

export type GetV2CarbonSummaryResponse = GetV2CarbonSummaryResponses[keyof GetV2CarbonSummaryResponses];

export type GetV2CircuitBreakersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/circuit-breakers/';
};

export type GetV2CircuitBreakersResponses = {
    /**
     * Default Response
     */
    200: Array<{
        failureCount?: number;
        failureRate?: number;
        lastStateChange?: string;
        name?: string;
        nextRetryAt?: string;
        state?: 'CLOSED' | 'HALF_OPEN' | 'OPEN';
        successCount?: number;
    }>;
};

export type GetV2CircuitBreakersResponse = GetV2CircuitBreakersResponses[keyof GetV2CircuitBreakersResponses];

export type PostV2CircuitBreakersByNameResetData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/v2/circuit-breakers/{name}/reset';
};

export type PostV2CircuitBreakersByNameResetErrors = {
    /**
     * Default Response
     */
    404: Def0;
};

export type PostV2CircuitBreakersByNameResetError = PostV2CircuitBreakersByNameResetErrors[keyof PostV2CircuitBreakersByNameResetErrors];

export type PostV2CircuitBreakersByNameResetResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
        success?: boolean;
    };
};

export type PostV2CircuitBreakersByNameResetResponse = PostV2CircuitBreakersByNameResetResponses[keyof PostV2CircuitBreakersByNameResetResponses];

export type GetV2CostByNodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cost/by-node';
};

export type GetV2CostByNodeResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2CostProjectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cost/projections';
};

export type GetV2CostProjectionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2CostRecordsData = {
    body?: never;
    path?: never;
    query?: {
        nodeId?: string;
        resourceType?: string;
        from?: Date;
        to?: Date;
        granularity?: 'day' | 'hour' | 'month' | 'week';
    };
    url: '/v2/cost/records';
};

export type GetV2CostRecordsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2CostSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/cost/summary';
};

export type GetV2CostSummaryResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2FlModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/fl/models';
};

export type GetV2FlModelsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2FlModelsData = {
    body: {
        architecture: string;
        name: string;
        parameters: number;
        version: string;
        weightsSize?: number;
        weightsUrl?: string;
    };
    path?: never;
    query?: never;
    url: '/v2/fl/models';
};

export type PostV2FlModelsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2FlModelsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/fl/models/{id}';
};

export type GetV2FlModelsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2FlModelsByIdWeightsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/fl/models/{id}/weights';
};

export type GetV2FlModelsByIdWeightsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2FlModelsByIdWeightsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/fl/models/{id}/weights';
};

export type PostV2FlModelsByIdWeightsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2FlSessionsData = {
    body: {
        config?: {
            aggregationStrategy?: 'fedadam' | 'fedavg' | 'fedprox';
            gradientClipNorm?: number;
            learningRate?: number;
            localEpochs?: number;
            maxClients?: number;
            minClients?: number;
            noiseMultiplier?: number;
            privacyBudget?: number;
        };
        modelId: string;
        totalRounds?: number;
    };
    path?: never;
    query?: never;
    url: '/v2/fl/sessions';
};

export type PostV2FlSessionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2FlSessionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/fl/sessions/{id}';
};

export type GetV2FlSessionsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2FlSessionsByIdStopData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/fl/sessions/{id}/stop';
};

export type PostV2FlSessionsByIdStopResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2LogsData = {
    body?: never;
    path?: never;
    query?: {
        taskId?: string;
        nodeId?: string;
        level?: 'DEBUG' | 'ERROR' | 'INFO' | 'WARN';
        limit?: number;
        offset?: number;
    };
    url: '/v2/logs/';
};

export type GetV2LogsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2LogsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/logs/stats';
};

export type GetV2LogsStatsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/';
};

export type GetV2MetricsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MetricsMlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/ml';
};

export type GetV2MetricsMlResponses = {
    /**
     * Default Response
     */
    200: {
        activeModels?: number;
        avgAccuracy?: number;
        totalPredictions?: number;
        trainingJobs?: number;
    };
};

export type GetV2MetricsMlResponse = GetV2MetricsMlResponses[keyof GetV2MetricsMlResponses];

export type GetV2MetricsNetworkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/network';
};

export type GetV2MetricsNetworkResponses = {
    /**
     * Default Response
     */
    200: {
        avgLatency?: number;
        egressGbps?: number;
        ingressGbps?: number;
        packetLoss?: number;
    };
};

export type GetV2MetricsNetworkResponse = GetV2MetricsNetworkResponses[keyof GetV2MetricsNetworkResponses];

export type GetV2MetricsNodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/nodes';
};

export type GetV2MetricsNodesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MetricsPrometheusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/prometheus';
};

export type GetV2MetricsPrometheusResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MetricsRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/requests';
};

export type GetV2MetricsRequestsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MetricsSystemData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/metrics/system';
};

export type GetV2MetricsSystemErrors = {
    /**
     * Default Response
     */
    401: Def0;
};

export type GetV2MetricsSystemError = GetV2MetricsSystemErrors[keyof GetV2MetricsSystemErrors];

export type GetV2MlDriftCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/drift/current';
};

export type GetV2MlDriftCurrentResponses = {
    /**
     * Default Response
     */
    200: {
        driftScore?: number;
        featureDrift?: {
            [key: string]: number;
        };
        isDrifting?: boolean;
        lastCheckedAt?: string;
    };
};

export type GetV2MlDriftCurrentResponse = GetV2MlDriftCurrentResponses[keyof GetV2MlDriftCurrentResponses];

export type GetV2MlDriftHistoryData = {
    body?: never;
    path?: never;
    query?: {
        hours?: number;
    };
    url: '/v2/ml/drift/history';
};

export type GetV2MlDriftHistoryResponses = {
    /**
     * Default Response
     */
    200: Array<{
        score?: number;
        timestamp?: string;
    }>;
};

export type GetV2MlDriftHistoryResponse = GetV2MlDriftHistoryResponses[keyof GetV2MlDriftHistoryResponses];

export type GetV2MlFederatedModelByModelIdWeightsData = {
    body?: never;
    path: {
        modelId: string;
    };
    query?: never;
    url: '/v2/ml/federated/model/{modelId}/weights';
};

export type GetV2MlFederatedModelByModelIdWeightsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MlFederatedRoundData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/federated/round';
};

export type GetV2MlFederatedRoundResponses = {
    /**
     * Default Response
     */
    200: {
        minParticipants?: number;
        modelId?: string;
        roundId?: string;
        roundNumber?: number;
        status?: string;
        submissionsCount?: number;
    };
};

export type GetV2MlFederatedRoundResponse = GetV2MlFederatedRoundResponses[keyof GetV2MlFederatedRoundResponses];

export type PostV2MlFederatedWeightsData = {
    body: {
        avgReward?: number | null;
        nodeId: string;
        roundId: string;
        sampleCount: number;
        weightsUrl: string;
    };
    path?: never;
    query?: never;
    url: '/v2/ml/federated/weights';
};

export type PostV2MlFederatedWeightsResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
        success?: boolean;
    };
};

export type PostV2MlFederatedWeightsResponse = PostV2MlFederatedWeightsResponses[keyof PostV2MlFederatedWeightsResponses];

export type PostV2MlFederatedWeightsUploadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/federated/weights/upload';
};

export type PostV2MlFederatedWeightsUploadResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2MlModelCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/model/current';
};

export type GetV2MlModelCurrentResponses = {
    /**
     * Default Response
     */
    200: {
        accuracy?: number;
        fallbackRate?: number;
        lastUpdatedAt?: string;
        modelType?: string;
        trainedAt?: string;
        version?: string;
    };
};

export type GetV2MlModelCurrentResponse = GetV2MlModelCurrentResponses[keyof GetV2MlModelCurrentResponses];

export type GetV2MlOutcomesStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/outcomes/stats';
};

export type GetV2MlOutcomesStatsResponses = {
    /**
     * Default Response
     */
    200: {
        banditExplorationRate?: number;
        nextUpdateAt?: number;
        outcomesBuffered?: number;
        predictionErrorP99Ms?: number;
    };
};

export type GetV2MlOutcomesStatsResponse = GetV2MlOutcomesStatsResponses[keyof GetV2MlOutcomesStatsResponses];

export type PostV2MlRetrainData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/retrain';
};

export type PostV2MlRetrainResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
        success?: boolean;
    };
};

export type PostV2MlRetrainResponse = PostV2MlRetrainResponses[keyof PostV2MlRetrainResponses];

export type GetV2MlRetrainStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/ml/retrain/status';
};

export type GetV2MlRetrainStatusResponses = {
    /**
     * Default Response
     */
    200: {
        error?: string | null;
        lastStartedAt?: string;
        status?: string;
    };
};

export type GetV2MlRetrainStatusResponse = GetV2MlRetrainStatusResponses[keyof GetV2MlRetrainStatusResponses];

export type GetV2NodesData = {
    body?: never;
    path?: never;
    query?: {
        region?: string;
        status?: 'DEGRADED' | 'MAINTENANCE' | 'OFFLINE' | 'ONLINE';
        page?: number;
        limit?: number;
        sortBy?: 'createdAt' | 'name' | 'region' | 'status';
        sortOrder?: 'asc' | 'desc';
    };
    url: '/v2/nodes/';
};

export type GetV2NodesResponses = {
    /**
     * Default Response
     */
    200: {
        data?: Array<{
            id: string;
            ipAddress: string;
            lastHeartbeat: Date;
            load?: {
                activeTasks: number;
                cpuUsage?: number;
                memoryUsage?: number;
            };
            location: string;
            name: string;
            port: number;
            region: string;
            specs: {
                cpuCores: number;
                memoryGB: number;
                storageGB: number;
            };
            status: 'DEGRADED' | 'MAINTENANCE' | 'OFFLINE' | 'ONLINE';
        }>;
        pagination?: {
            limit?: number;
            page?: number;
            total?: number;
            totalPages?: number;
        };
    };
};

export type GetV2NodesResponse = GetV2NodesResponses[keyof GetV2NodesResponses];

export type PostV2NodesData = {
    body: {
        bandwidthInMbps?: number;
        bandwidthOutMbps?: number;
        costPerHour?: number;
        cpuCores: number;
        ipAddress: string;
        location: string;
        maxTasks?: number;
        memoryGB: number;
        name: string;
        port: number;
        region: string;
        storageGB: number;
    };
    path?: never;
    query?: never;
    url: '/v2/nodes/';
};

export type PostV2NodesErrors = {
    /**
     * Default Response
     */
    409: Def0;
};

export type PostV2NodesError = PostV2NodesErrors[keyof PostV2NodesErrors];

export type PostV2NodesResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        ipAddress: string;
        lastHeartbeat: Date;
        load?: {
            activeTasks: number;
            cpuUsage?: number;
            memoryUsage?: number;
        };
        location: string;
        name: string;
        port: number;
        region: string;
        specs: {
            cpuCores: number;
            memoryGB: number;
            storageGB: number;
        };
        status: 'DEGRADED' | 'MAINTENANCE' | 'OFFLINE' | 'ONLINE';
    };
};

export type PostV2NodesResponse = PostV2NodesResponses[keyof PostV2NodesResponses];

export type DeleteV2NodesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}';
};

export type DeleteV2NodesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2NodesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}';
};

export type GetV2NodesByIdErrors = {
    /**
     * Default Response
     */
    404: Def0;
};

export type GetV2NodesByIdError = GetV2NodesByIdErrors[keyof GetV2NodesByIdErrors];

export type GetV2NodesByIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        ipAddress: string;
        lastHeartbeat: Date;
        load?: {
            activeTasks: number;
            cpuUsage?: number;
            memoryUsage?: number;
        };
        location: string;
        name: string;
        port: number;
        region: string;
        specs: {
            cpuCores: number;
            memoryGB: number;
            storageGB: number;
        };
        status: 'DEGRADED' | 'MAINTENANCE' | 'OFFLINE' | 'ONLINE';
    };
};

export type GetV2NodesByIdResponse = GetV2NodesByIdResponses[keyof GetV2NodesByIdResponses];

export type PatchV2NodesByIdData = {
    body?: {
        costPerHour?: number;
        cpuCores?: number;
        isMaintenanceMode?: boolean;
        location?: string;
        maxTasks?: number;
        memoryGB?: number;
        name?: string;
        region?: string;
        storageGB?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}';
};

export type PatchV2NodesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2NodesByIdDrainData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}/drain';
};

export type PostV2NodesByIdDrainResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
        success?: boolean;
    };
};

export type PostV2NodesByIdDrainResponse = PostV2NodesByIdDrainResponses[keyof PostV2NodesByIdDrainResponses];

export type PostV2NodesByIdHeartbeatData = {
    body: {
        cpuUsage: number;
        latency?: number;
        memoryUsage: number;
        networkIn?: number;
        networkOut?: number;
        storageUsage?: number;
        tasksRunning?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}/heartbeat';
};

export type PostV2NodesByIdHeartbeatResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2NodesByIdMaintenanceData = {
    body: {
        enabled: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}/maintenance';
};

export type PostV2NodesByIdMaintenanceResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2NodesByIdMetricsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        from?: Date;
        to?: Date;
        limit?: number;
    };
    url: '/v2/nodes/{id}/metrics';
};

export type GetV2NodesByIdMetricsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2NodesByIdOfflineData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/nodes/{id}/offline';
};

export type PostV2NodesByIdOfflineResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
        success?: boolean;
    };
};

export type PostV2NodesByIdOfflineResponse = PostV2NodesByIdOfflineResponses[keyof PostV2NodesByIdOfflineResponses];

export type GetV2NodesByIdSchedulingHistoryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        days?: number;
    };
    url: '/v2/nodes/{id}/scheduling-history';
};

export type GetV2NodesByIdSchedulingHistoryResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2PoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/policies/';
};

export type GetV2PoliciesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2PoliciesActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/policies/active';
};

export type GetV2PoliciesActiveResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV2PoliciesActiveData = {
    body: {
        policy: string;
    };
    path?: never;
    query?: never;
    url: '/v2/policies/active';
};

export type PatchV2PoliciesActiveResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2PoliciesConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/policies/config';
};

export type GetV2PoliciesConfigResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2PoliciesThresholdsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/policies/thresholds';
};

export type GetV2PoliciesThresholdsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV2PoliciesThresholdsData = {
    body?: {
        cpu?: number;
        latency?: number;
        memory?: number;
    };
    path?: never;
    query?: never;
    url: '/v2/policies/thresholds';
};

export type PatchV2PoliciesThresholdsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2SchedulerDecisionsData = {
    body?: never;
    path?: never;
    query?: {
        nodeId?: string;
        limit?: number;
    };
    url: '/v2/scheduler/decisions';
};

export type GetV2SchedulerDecisionsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2SchedulerMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/scheduler/metrics';
};

export type GetV2SchedulerMetricsResponses = {
    /**
     * Default Response
     */
    200: {
        avgSchedulingTime?: number;
        efficiency?: number;
        queueLength?: number;
        throughput?: number;
    };
};

export type GetV2SchedulerMetricsResponse = GetV2SchedulerMetricsResponses[keyof GetV2SchedulerMetricsResponses];

export type GetV2SchedulingPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/scheduling/policy';
};

export type GetV2SchedulingPolicyResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV2SchedulingPolicyData = {
    body: {
        carbonWeight: number;
        costWeight: number;
        latencyWeight: number;
    };
    path?: never;
    query?: never;
    url: '/v2/scheduling/policy';
};

export type PutV2SchedulingPolicyResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/status';
};

export type GetV2StatusResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2SystemCircuitBreakersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/system/circuit-breakers';
};

export type GetV2SystemCircuitBreakersResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2SystemInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/system/info';
};

export type GetV2SystemInfoResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2TasksData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'CANCELLED' | 'COMPLETED' | 'FAILED' | 'PENDING' | 'RUNNING' | 'SCHEDULED';
        type?: string;
        nodeId?: string;
        priority?: 'CRITICAL' | 'HIGH' | 'LOW' | 'MEDIUM';
        page?: number;
        limit?: number;
        sortBy?: 'createdAt' | 'duration' | 'name' | 'priority' | 'status' | 'submittedAt' | 'updatedAt';
        sortOrder?: 'asc' | 'desc';
        from?: Date;
        to?: Date;
    };
    url: '/v2/tasks/';
};

export type GetV2TasksResponses = {
    /**
     * Default Response
     */
    200: {
        data?: Array<{
            affinity?: unknown | string | unknown;
            completedAt?: unknown | Date | unknown;
            error?: unknown | string | unknown;
            id: string;
            image?: unknown | string | unknown;
            metadata?: {
                [key: string]: unknown;
            };
            name: string;
            nodeId?: unknown | string | unknown;
            priority: string;
            runtime: 'DOCKER' | 'NATIVE' | 'WASM';
            specs?: unknown | {
                cpuCores: number;
                memoryGB: number;
            } | unknown;
            startedAt?: unknown | Date | unknown;
            status: 'CANCELLED' | 'COMPLETED' | 'FAILED' | 'PENDING' | 'RUNNING' | 'SCHEDULED';
            submittedAt: Date;
            traceId?: unknown | string | unknown;
            type: string;
            wasmArtifactId?: unknown | string | unknown;
        }>;
        pagination?: {
            limit?: number;
            page?: number;
            total?: number;
            totalPages?: number;
        };
    };
};

export type GetV2TasksResponse = GetV2TasksResponses[keyof GetV2TasksResponses];

export type PostV2TasksData = {
    body: {
        affinity?: string;
        image?: string;
        input?: {
            [key: string]: unknown;
        };
        isDeferrable?: boolean;
        maxDelayMinutes?: number;
        maxRetries?: number;
        metadata?: {
            [key: string]: unknown;
        };
        name: string;
        nodeId?: string;
        policy?: string;
        priority?: 'CRITICAL' | 'HIGH' | 'LOW' | 'MEDIUM';
        runtime?: 'DOCKER' | 'NATIVE' | 'WASM';
        specs?: {
            cpuCores?: number;
            memoryGB?: number;
            memoryMB?: number;
        };
        target?: 'CLOUD' | 'EDGE' | 'HYBRID';
        traceId?: string;
        type: 'ANOMALY_DETECTION' | 'BATCH_PROCESSING' | 'CICD_PIPELINE' | 'COMPUTER_VISION' | 'CONTAINER_BUILD' | 'CUSTOM' | 'DATA_AGGREGATION' | 'DATA_PROCESSING' | 'ETL_PIPELINE' | 'FRAUD_DETECTION' | 'IMAGE_CLASSIFICATION' | 'IOT_DATA_INGESTION' | 'LOG_ANALYSIS' | 'ML_TRAINING' | 'MODEL_INFERENCE' | 'NLP' | 'REALTIME_ANALYTICS' | 'RECOMMENDATION_ENGINE' | 'SENSOR_FUSION' | 'SPEECH_RECOGNITION' | 'VIDEO_PROCESSING';
        wasmArtifactId?: string;
    };
    path?: never;
    query?: never;
    url: '/v2/tasks/';
};

export type PostV2TasksErrors = {
    /**
     * Default Response
     */
    400: Def0;
    /**
     * Default Response
     */
    409: Def0;
};

export type PostV2TasksError = PostV2TasksErrors[keyof PostV2TasksErrors];

export type PostV2TasksResponses = {
    /**
     * Default Response
     */
    201: {
        affinity?: unknown | string | unknown;
        completedAt?: unknown | Date | unknown;
        error?: unknown | string | unknown;
        id: string;
        image?: unknown | string | unknown;
        metadata?: {
            [key: string]: unknown;
        };
        name: string;
        nodeId?: unknown | string | unknown;
        priority: string;
        runtime: 'DOCKER' | 'NATIVE' | 'WASM';
        specs?: unknown | {
            cpuCores: number;
            memoryGB: number;
        } | unknown;
        startedAt?: unknown | Date | unknown;
        status: 'CANCELLED' | 'COMPLETED' | 'FAILED' | 'PENDING' | 'RUNNING' | 'SCHEDULED';
        submittedAt: Date;
        traceId?: unknown | string | unknown;
        type: string;
        wasmArtifactId?: unknown | string | unknown;
    };
};

export type PostV2TasksResponse = PostV2TasksResponses[keyof PostV2TasksResponses];

export type PostV2TasksArtifactsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/tasks/artifacts';
};

export type PostV2TasksArtifactsErrors = {
    /**
     * Default Response
     */
    400: Def0;
};

export type PostV2TasksArtifactsError = PostV2TasksArtifactsErrors[keyof PostV2TasksArtifactsErrors];

export type PostV2TasksArtifactsResponses = {
    /**
     * Default Response
     */
    201: {
        artifactId?: string;
    };
};

export type PostV2TasksArtifactsResponse = PostV2TasksArtifactsResponses[keyof PostV2TasksArtifactsResponses];

export type GetV2TasksArtifactsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/tasks/artifacts/{id}';
};

export type GetV2TasksArtifactsByIdErrors = {
    /**
     * Default Response
     */
    404: Def0;
};

export type GetV2TasksArtifactsByIdError = GetV2TasksArtifactsByIdErrors[keyof GetV2TasksArtifactsByIdErrors];

export type GetV2TasksArtifactsByIdResponses = {
    /**
     * Default Response
     */
    200: Blob | File;
};

export type GetV2TasksArtifactsByIdResponse = GetV2TasksArtifactsByIdResponses[keyof GetV2TasksArtifactsByIdResponses];

export type GetV2TasksStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/tasks/stats';
};

export type GetV2TasksStatsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2TasksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/tasks/{id}';
};

export type GetV2TasksByIdErrors = {
    /**
     * Default Response
     */
    404: Def0;
};

export type GetV2TasksByIdError = GetV2TasksByIdErrors[keyof GetV2TasksByIdErrors];

export type GetV2TasksByIdResponses = {
    /**
     * Default Response
     */
    200: {
        affinity?: unknown | string | unknown;
        completedAt?: unknown | Date | unknown;
        error?: unknown | string | unknown;
        id: string;
        image?: unknown | string | unknown;
        metadata?: {
            [key: string]: unknown;
        };
        name: string;
        nodeId?: unknown | string | unknown;
        priority: string;
        runtime: 'DOCKER' | 'NATIVE' | 'WASM';
        specs?: unknown | {
            cpuCores: number;
            memoryGB: number;
        } | unknown;
        startedAt?: unknown | Date | unknown;
        status: 'CANCELLED' | 'COMPLETED' | 'FAILED' | 'PENDING' | 'RUNNING' | 'SCHEDULED';
        submittedAt: Date;
        traceId?: unknown | string | unknown;
        type: string;
        wasmArtifactId?: unknown | string | unknown;
    };
};

export type GetV2TasksByIdResponse = GetV2TasksByIdResponses[keyof GetV2TasksByIdResponses];

export type PostV2TasksByIdCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/tasks/{id}/cancel';
};

export type PostV2TasksByIdCancelResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2TasksByIdLogsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        level?: string;
        limit?: number;
    };
    url: '/v2/tasks/{id}/logs';
};

export type GetV2TasksByIdLogsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2TasksByIdRetryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/tasks/{id}/retry';
};

export type PostV2TasksByIdRetryResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2TasksByIdSchedulingDecisionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/tasks/{id}/scheduling-decision';
};

export type GetV2TasksByIdSchedulingDecisionResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2WebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/webhooks/';
};

export type GetV2WebhooksResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2WebhooksData = {
    body: {
        enabled?: boolean;
        events: Array<string>;
        name: string;
        secret?: string;
        url: string;
    };
    path?: never;
    query?: never;
    url: '/v2/webhooks/';
};

export type PostV2WebhooksResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2WebhooksDeliveriesByIdRetryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/webhooks/deliveries/{id}/retry';
};

export type PostV2WebhooksDeliveriesByIdRetryResponses = {
    /**
     * Default Response
     */
    200: {
        message?: string;
        success?: boolean;
    };
};

export type PostV2WebhooksDeliveriesByIdRetryResponse = PostV2WebhooksDeliveriesByIdRetryResponses[keyof PostV2WebhooksDeliveriesByIdRetryResponses];

export type GetV2WebhooksStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/webhooks/stats';
};

export type GetV2WebhooksStatsResponses = {
    /**
     * Default Response
     */
    200: {
        active?: number;
        avgLatency?: number;
        failedLast24h?: number;
        total?: number;
    };
};

export type GetV2WebhooksStatsResponse = GetV2WebhooksStatsResponses[keyof GetV2WebhooksStatsResponses];

export type DeleteV2WebhooksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/webhooks/{id}';
};

export type DeleteV2WebhooksByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV2WebhooksByIdData = {
    body?: {
        enabled?: boolean;
        events?: Array<string>;
        name?: string;
        secret?: string;
        url?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/webhooks/{id}';
};

export type PatchV2WebhooksByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2WebhooksByIdDeliveriesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
    };
    url: '/v2/webhooks/{id}/deliveries';
};

export type GetV2WebhooksByIdDeliveriesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2WebhooksByIdRedeliverByDeliveryIdData = {
    body?: never;
    path: {
        id: string;
        deliveryId: string;
    };
    query?: never;
    url: '/v2/webhooks/{id}/redeliver/{deliveryId}';
};

export type PostV2WebhooksByIdRedeliverByDeliveryIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2WebhooksByIdTestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/webhooks/{id}/test';
};

export type PostV2WebhooksByIdTestResponses = {
    /**
     * Default Response
     */
    200: {
        deliveryId?: string;
        success?: boolean;
    };
};

export type PostV2WebhooksByIdTestResponse = PostV2WebhooksByIdTestResponses[keyof PostV2WebhooksByIdTestResponses];

export type GetV2WorkflowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/workflows/';
};

export type GetV2WorkflowsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2WorkflowsData = {
    body: {
        edges: Array<{
            condition?: string;
            from: string;
            id: string;
            to: string;
        }>;
        name: string;
        nodes: Array<{
            config: {
                [key: string]: unknown;
            };
            id: string;
            inputs: Array<string>;
            name: string;
            outputs: Array<string>;
            type: 'decision' | 'parallel' | 'subworkflow' | 'task' | 'wait';
        }>;
        retryPolicy?: {
            initialDelay?: number;
            maxDelay?: number;
            maxRetries?: number;
            multiplier?: number;
        };
        timeout?: number;
        variables?: {
            [key: string]: unknown;
        };
        version: string;
    };
    path?: never;
    query?: never;
    url: '/v2/workflows/';
};

export type PostV2WorkflowsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2WorkflowsExecutionsByExecutionIdData = {
    body?: never;
    path: {
        executionId: string;
    };
    query?: never;
    url: '/v2/workflows/executions/{executionId}';
};

export type GetV2WorkflowsExecutionsByExecutionIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV2WorkflowsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/workflows/{id}';
};

export type GetV2WorkflowsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV2WorkflowsByIdExecuteData = {
    body?: {
        input?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v2/workflows/{id}/execute';
};

export type PostV2WorkflowsByIdExecuteResponses = {
    /**
     * Default Response
     */
    200: unknown;
};
