// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ErrorSchema
 */
export type Def0 = {
  /**
   * Machine-readable error code
   */
  code: string;
  /**
   * Human-readable error description
   */
  message: string;
  /**
   * Unique request ID
   */
  requestId: string;
  /**
   * ISO 8601 timestamp
   */
  timestamp: Date;
  /**
   * Optional error details
   */
  details?: unknown;
  /**
   * Error stack trace (non-production only)
   */
  stack?: string;
};

/**
 * HealthSchema
 */
export type Def1 = {
  status: "healthy" | "degraded" | "unhealthy";
  service: string;
  timestamp: Date;
  checks?: {
    [key: string]: boolean;
  };
  version?: string;
};

export type GetV2AdminAuditLogsData = {
  body?: never;
  path?: never;
  query?: {
    userId?: string;
    action?: string;
    limit?: number;
  };
  url: "/v2/admin/audit-logs";
};

export type GetV2AdminAuditLogsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AdminCleanupData = {
  body: {
    olderThanDays: number;
    types: Array<string>;
  };
  path?: never;
  query?: never;
  url: "/v2/admin/cleanup";
};

export type PostV2AdminCleanupResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AdminDlqEventsData = {
  body?: never;
  path?: never;
  query?: {
    topic?: string;
    status?: "PENDING" | "RETRYING" | "REPROCESSED" | "PERMANENTLY_FAILED";
    limit?: number;
    offset?: number;
  };
  url: "/v2/admin/dlq/events";
};

export type GetV2AdminDlqEventsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AdminDlqEventsByIdRetryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/admin/dlq/events/{id}/retry";
};

export type PostV2AdminDlqEventsByIdRetryResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AdminDlqPurgeData = {
  body?: {
    olderThanDays?: number;
  };
  path?: never;
  query?: never;
  url: "/v2/admin/dlq/purge";
};

export type PostV2AdminDlqPurgeResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AdminDlqStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/admin/dlq/stats";
};

export type GetV2AdminDlqStatsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AdminHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/admin/health";
};

export type GetV2AdminHealthResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AdminMlRetrainData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/admin/ml/retrain";
};

export type PostV2AdminMlRetrainResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AdminUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/admin/users";
};

export type GetV2AdminUsersResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AdminUsersByIdDeactivateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/admin/users/{id}/deactivate";
};

export type PostV2AdminUsersByIdDeactivateResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PatchV2AdminUsersByIdRoleData = {
  body: {
    role: "ADMIN" | "OPERATOR" | "VIEWER";
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/admin/users/{id}/role";
};

export type PatchV2AdminUsersByIdRoleResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AgentsCaData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/agents/ca";
};

export type GetV2AgentsCaResponses = {
  /**
   * Default Response
   */
  200: {
    certificate?: string;
  };
};

export type GetV2AgentsCaResponse =
  GetV2AgentsCaResponses[keyof GetV2AgentsCaResponses];

export type PostV2AgentsCertificatesSignData = {
  body: {
    /**
     * PEM encoded Certificate Signing Request
     */
    csr: string;
    /**
     * One-time bootstrap token
     */
    bootstrapToken: string;
    nodeName: string;
    region: string;
    ipAddress?: string;
    port?: number;
    cpuCores?: number;
    memoryGB?: number;
    storageGB?: number;
    hardwareId?: string;
  };
  path?: never;
  query?: never;
  url: "/v2/agents/certificates/sign";
};

export type PostV2AgentsCertificatesSignErrors = {
  /**
   * Default Response
   */
  400: Def0;
  /**
   * Default Response
   */
  401: Def0;
  /**
   * Default Response
   */
  403: Def0;
};

export type PostV2AgentsCertificatesSignError =
  PostV2AgentsCertificatesSignErrors[keyof PostV2AgentsCertificatesSignErrors];

export type PostV2AgentsCertificatesSignResponses = {
  /**
   * Default Response
   */
  200: {
    certificate?: string;
    caCertificate?: string;
    nodeId?: string;
    expiresAt?: Date;
  };
};

export type PostV2AgentsCertificatesSignResponse =
  PostV2AgentsCertificatesSignResponses[keyof PostV2AgentsCertificatesSignResponses];

export type PostV2AgentsHeartbeatData = {
  body?: {
    timestamp?: number;
    status?: string;
    metrics?: {
      cpu_usage?: number;
      memory_usage?: number;
    };
  };
  path?: never;
  query?: never;
  url: "/v2/agents/heartbeat";
};

export type PostV2AgentsHeartbeatResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AgentsTasksPendingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/agents/tasks/pending";
};

export type GetV2AgentsTasksPendingErrors = {
  /**
   * Default Response
   */
  404: {
    message?: string;
  };
};

export type GetV2AgentsTasksPendingError =
  GetV2AgentsTasksPendingErrors[keyof GetV2AgentsTasksPendingErrors];

export type GetV2AgentsTasksPendingResponses = {
  /**
   * Default Response
   */
  200: {
    task_id?: string;
    runtime?: string;
    image?: string;
    input?: {
      [key: string]: unknown;
    };
    memory_limit_mb?: number;
    cpu_fuel?: number | null;
    timeout_seconds?: number;
  };
};

export type GetV2AgentsTasksPendingResponse =
  GetV2AgentsTasksPendingResponses[keyof GetV2AgentsTasksPendingResponses];

export type PostV2AgentsTasksByTaskIdResultData = {
  body: {
    status: string;
    exit_code: number;
    stdout?: string;
    stderr?: string;
    duration_ms?: number;
    error?: string | null;
  };
  path: {
    taskId: string;
  };
  query?: never;
  url: "/v2/agents/tasks/{taskId}/result";
};

export type PostV2AgentsTasksByTaskIdResultResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type DeleteV2AlertsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/alerts/";
};

export type DeleteV2AlertsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2AlertsData = {
  body?: never;
  path?: never;
  query?: {
    severity?: "critical" | "warning" | "info";
  };
  url: "/v2/alerts/";
};

export type GetV2AlertsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AlertsTestData = {
  body: {
    severity: "critical" | "warning" | "info";
    title: string;
    message: string;
  };
  path?: never;
  query?: never;
  url: "/v2/alerts/test";
};

export type PostV2AlertsTestResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AuthLoginData = {
  body: {
    email: string;
    password: string;
  };
  path?: never;
  query?: never;
  url: "/v2/auth/login";
};

export type PostV2AuthLoginErrors = {
  /**
   * Default Response
   */
  401: Def0;
  /**
   * Default Response
   */
  429: Def0;
};

export type PostV2AuthLoginError =
  PostV2AuthLoginErrors[keyof PostV2AuthLoginErrors];

export type PostV2AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/auth/logout";
};

export type PostV2AuthLogoutResponses = {
  /**
   * Default Response
   */
  200: {
    success?: boolean;
  };
};

export type PostV2AuthLogoutResponse =
  PostV2AuthLogoutResponses[keyof PostV2AuthLogoutResponses];

export type GetV2AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/auth/me";
};

export type GetV2AuthMeResponses = {
  /**
   * Default Response
   */
  200: {
    id?: string;
    email?: string;
    name?: string;
    role?: string;
    createdAt?: string;
    lastLoginAt?: string | null;
  };
};

export type GetV2AuthMeResponse =
  GetV2AuthMeResponses[keyof GetV2AuthMeResponses];

export type PostV2AuthRefreshData = {
  body: {
    refreshToken: string;
  };
  path?: never;
  query?: never;
  url: "/v2/auth/refresh";
};

export type PostV2AuthRefreshResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2AuthRegisterData = {
  body: {
    email: string;
    password: unknown & unknown & unknown;
    name: string;
  };
  path?: never;
  query?: never;
  url: "/v2/auth/register";
};

export type PostV2AuthRegisterErrors = {
  /**
   * Default Response
   */
  400: Def0;
  /**
   * Default Response
   */
  409: Def0;
};

export type PostV2AuthRegisterError =
  PostV2AuthRegisterErrors[keyof PostV2AuthRegisterErrors];

export type GetV2CarbonByRegionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/carbon/by-region";
};

export type GetV2CarbonByRegionResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2CarbonMetricsData = {
  body?: never;
  path?: never;
  query?: {
    region?: string;
    from?: Date;
    to?: Date;
    granularity?: "hour" | "day" | "week" | "month";
  };
  url: "/v2/carbon/metrics";
};

export type GetV2CarbonMetricsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2CarbonRecordData = {
  body: {
    nodeId?: string;
    region: string;
    energyKwh: number;
    carbonKg: number;
    renewablePercent?: number;
  };
  path?: never;
  query?: never;
  url: "/v2/carbon/record";
};

export type PostV2CarbonRecordResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2CarbonSummaryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/carbon/summary";
};

export type GetV2CarbonSummaryResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2CostByNodeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/cost/by-node";
};

export type GetV2CostByNodeResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2CostProjectionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/cost/projections";
};

export type GetV2CostProjectionsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2CostRecordsData = {
  body?: never;
  path?: never;
  query?: {
    nodeId?: string;
    resourceType?: string;
    from?: Date;
    to?: Date;
    granularity?: "hour" | "day" | "week" | "month";
  };
  url: "/v2/cost/records";
};

export type GetV2CostRecordsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2CostSummaryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/cost/summary";
};

export type GetV2CostSummaryResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2FlModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/fl/models";
};

export type GetV2FlModelsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2FlModelsData = {
  body: {
    name: string;
    version: string;
    architecture: string;
    parameters: number;
    weightsUrl?: string;
    weightsSize?: number;
  };
  path?: never;
  query?: never;
  url: "/v2/fl/models";
};

export type PostV2FlModelsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2FlModelsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/fl/models/{id}";
};

export type GetV2FlModelsByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2FlModelsByIdWeightsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/fl/models/{id}/weights";
};

export type GetV2FlModelsByIdWeightsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2FlModelsByIdWeightsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/fl/models/{id}/weights";
};

export type PostV2FlModelsByIdWeightsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2FlSessionsData = {
  body: {
    modelId: string;
    totalRounds?: number;
    config?: {
      minClients?: number;
      maxClients?: number;
      localEpochs?: number;
      learningRate?: number;
      aggregationStrategy?: "fedavg" | "fedprox" | "fedadam";
      privacyBudget?: number;
      noiseMultiplier?: number;
      gradientClipNorm?: number;
    };
  };
  path?: never;
  query?: never;
  url: "/v2/fl/sessions";
};

export type PostV2FlSessionsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2FlSessionsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/fl/sessions/{id}";
};

export type GetV2FlSessionsByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2FlSessionsByIdStopData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/fl/sessions/{id}/stop";
};

export type PostV2FlSessionsByIdStopResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2LogsData = {
  body?: never;
  path?: never;
  query?: {
    taskId?: string;
    nodeId?: string;
    level?: "DEBUG" | "INFO" | "WARN" | "ERROR";
    limit?: number;
    offset?: number;
  };
  url: "/v2/logs/";
};

export type GetV2LogsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2LogsStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/logs/stats";
};

export type GetV2LogsStatsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2MetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/";
};

export type GetV2MetricsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2MetricsMlData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/ml";
};

export type GetV2MetricsMlResponses = {
  /**
   * Default Response
   */
  200: {
    activeModels?: number;
    trainingJobs?: number;
    avgAccuracy?: number;
    totalPredictions?: number;
  };
};

export type GetV2MetricsMlResponse =
  GetV2MetricsMlResponses[keyof GetV2MetricsMlResponses];

export type GetV2MetricsNetworkData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/network";
};

export type GetV2MetricsNetworkResponses = {
  /**
   * Default Response
   */
  200: {
    ingressGbps?: number;
    egressGbps?: number;
    avgLatency?: number;
    packetLoss?: number;
  };
};

export type GetV2MetricsNetworkResponse =
  GetV2MetricsNetworkResponses[keyof GetV2MetricsNetworkResponses];

export type GetV2MetricsNodesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/nodes";
};

export type GetV2MetricsNodesResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2MetricsPrometheusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/prometheus";
};

export type GetV2MetricsPrometheusResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2MetricsRequestsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/requests";
};

export type GetV2MetricsRequestsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2MetricsSystemData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/metrics/system";
};

export type GetV2MetricsSystemErrors = {
  /**
   * Default Response
   */
  401: Def0;
};

export type GetV2MetricsSystemError =
  GetV2MetricsSystemErrors[keyof GetV2MetricsSystemErrors];

export type GetV2NodesData = {
  body?: never;
  path?: never;
  query?: {
    region?: string;
    status?: "ONLINE" | "OFFLINE" | "DEGRADED" | "MAINTENANCE";
    page?: number;
    limit?: number;
    sortBy?: "name" | "region" | "status" | "createdAt";
    sortOrder?: "asc" | "desc";
  };
  url: "/v2/nodes/";
};

export type GetV2NodesResponses = {
  /**
   * Default Response
   */
  200: {
    data?: Array<{
      id: string;
      name: string;
      location: string;
      region: string;
      status: "ONLINE" | "OFFLINE" | "DEGRADED" | "MAINTENANCE";
      ipAddress: string;
      port: number;
      specs: {
        cpuCores: number;
        memoryGB: number;
        storageGB: number;
      };
      load?: {
        cpuUsage?: number;
        memoryUsage?: number;
        activeTasks: number;
      };
      lastHeartbeat: Date;
    }>;
    pagination?: {
      page?: number;
      limit?: number;
      total?: number;
      totalPages?: number;
    };
  };
};

export type GetV2NodesResponse = GetV2NodesResponses[keyof GetV2NodesResponses];

export type PostV2NodesData = {
  body: {
    name: string;
    location: string;
    region: string;
    ipAddress: string;
    port: number;
    cpuCores: number;
    memoryGB: number;
    storageGB: number;
    costPerHour?: number;
    maxTasks?: number;
    bandwidthInMbps?: number;
    bandwidthOutMbps?: number;
  };
  path?: never;
  query?: never;
  url: "/v2/nodes/";
};

export type PostV2NodesErrors = {
  /**
   * Default Response
   */
  409: Def0;
};

export type PostV2NodesError = PostV2NodesErrors[keyof PostV2NodesErrors];

export type PostV2NodesResponses = {
  /**
   * Default Response
   */
  201: {
    id: string;
    name: string;
    location: string;
    region: string;
    status: "ONLINE" | "OFFLINE" | "DEGRADED" | "MAINTENANCE";
    ipAddress: string;
    port: number;
    specs: {
      cpuCores: number;
      memoryGB: number;
      storageGB: number;
    };
    load?: {
      cpuUsage?: number;
      memoryUsage?: number;
      activeTasks: number;
    };
    lastHeartbeat: Date;
  };
};

export type PostV2NodesResponse =
  PostV2NodesResponses[keyof PostV2NodesResponses];

export type DeleteV2NodesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}";
};

export type DeleteV2NodesByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2NodesByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}";
};

export type GetV2NodesByIdErrors = {
  /**
   * Default Response
   */
  404: Def0;
};

export type GetV2NodesByIdError =
  GetV2NodesByIdErrors[keyof GetV2NodesByIdErrors];

export type GetV2NodesByIdResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    name: string;
    location: string;
    region: string;
    status: "ONLINE" | "OFFLINE" | "DEGRADED" | "MAINTENANCE";
    ipAddress: string;
    port: number;
    specs: {
      cpuCores: number;
      memoryGB: number;
      storageGB: number;
    };
    load?: {
      cpuUsage?: number;
      memoryUsage?: number;
      activeTasks: number;
    };
    lastHeartbeat: Date;
  };
};

export type GetV2NodesByIdResponse =
  GetV2NodesByIdResponses[keyof GetV2NodesByIdResponses];

export type PatchV2NodesByIdData = {
  body?: {
    name?: string;
    location?: string;
    region?: string;
    cpuCores?: number;
    memoryGB?: number;
    storageGB?: number;
    costPerHour?: number;
    maxTasks?: number;
    isMaintenanceMode?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}";
};

export type PatchV2NodesByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2NodesByIdDrainData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}/drain";
};

export type PostV2NodesByIdDrainResponses = {
  /**
   * Default Response
   */
  200: {
    success?: boolean;
    message?: string;
  };
};

export type PostV2NodesByIdDrainResponse =
  PostV2NodesByIdDrainResponses[keyof PostV2NodesByIdDrainResponses];

export type PostV2NodesByIdHeartbeatData = {
  body: {
    cpuUsage: number;
    memoryUsage: number;
    storageUsage?: number;
    latency?: number;
    tasksRunning?: number;
    networkIn?: number;
    networkOut?: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}/heartbeat";
};

export type PostV2NodesByIdHeartbeatResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2NodesByIdMaintenanceData = {
  body: {
    enabled: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}/maintenance";
};

export type PostV2NodesByIdMaintenanceResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2NodesByIdMetricsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    from?: Date;
    to?: Date;
    limit?: number;
  };
  url: "/v2/nodes/{id}/metrics";
};

export type GetV2NodesByIdMetricsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2NodesByIdOfflineData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/nodes/{id}/offline";
};

export type PostV2NodesByIdOfflineResponses = {
  /**
   * Default Response
   */
  200: {
    success?: boolean;
    message?: string;
  };
};

export type PostV2NodesByIdOfflineResponse =
  PostV2NodesByIdOfflineResponses[keyof PostV2NodesByIdOfflineResponses];

export type GetV2NodesByIdSchedulingHistoryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    days?: number;
  };
  url: "/v2/nodes/{id}/scheduling-history";
};

export type GetV2NodesByIdSchedulingHistoryResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2PoliciesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/policies/";
};

export type GetV2PoliciesResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2PoliciesActiveData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/policies/active";
};

export type GetV2PoliciesActiveResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PatchV2PoliciesActiveData = {
  body: {
    policy: string;
  };
  path?: never;
  query?: never;
  url: "/v2/policies/active";
};

export type PatchV2PoliciesActiveResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2PoliciesConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/policies/config";
};

export type GetV2PoliciesConfigResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2PoliciesThresholdsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/policies/thresholds";
};

export type GetV2PoliciesThresholdsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PatchV2PoliciesThresholdsData = {
  body?: {
    cpu?: number;
    memory?: number;
    latency?: number;
  };
  path?: never;
  query?: never;
  url: "/v2/policies/thresholds";
};

export type PatchV2PoliciesThresholdsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2SchedulerMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/scheduler/metrics";
};

export type GetV2SchedulerMetricsResponses = {
  /**
   * Default Response
   */
  200: {
    queueLength?: number;
    avgSchedulingTime?: number;
    throughput?: number;
    efficiency?: number;
  };
};

export type GetV2SchedulerMetricsResponse =
  GetV2SchedulerMetricsResponses[keyof GetV2SchedulerMetricsResponses];

export type GetV2StatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/status";
};

export type GetV2StatusResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2SystemCircuitBreakersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/system/circuit-breakers";
};

export type GetV2SystemCircuitBreakersResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2SystemInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/system/info";
};

export type GetV2SystemInfoResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2TasksData = {
  body?: never;
  path?: never;
  query?: {
    status?:
      | "PENDING"
      | "SCHEDULED"
      | "RUNNING"
      | "COMPLETED"
      | "FAILED"
      | "CANCELLED";
    type?: string;
    nodeId?: string;
    priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
    page?: number;
    limit?: number;
    sortBy?:
      | "submittedAt"
      | "priority"
      | "status"
      | "duration"
      | "createdAt"
      | "updatedAt"
      | "name";
    sortOrder?: "asc" | "desc";
    from?: Date;
    to?: Date;
  };
  url: "/v2/tasks/";
};

export type GetV2TasksResponses = {
  /**
   * Default Response
   */
  200: {
    data?: Array<{
      id: string;
      name: string;
      type: string;
      status:
        | "PENDING"
        | "SCHEDULED"
        | "RUNNING"
        | "COMPLETED"
        | "FAILED"
        | "CANCELLED";
      priority: string;
      nodeId?: unknown | string | unknown;
      specs?:
        | unknown
        | {
            cpuCores: number;
            memoryGB: number;
          }
        | unknown;
      submittedAt: Date;
      startedAt?: unknown | Date | unknown;
      completedAt?: unknown | Date | unknown;
      error?: unknown | string | unknown;
      metadata?: {
        [key: string]: unknown;
      };
      runtime: "NATIVE" | "DOCKER" | "WASM";
      image: string;
      affinity?: unknown | string | unknown;
      traceId?: unknown | string | unknown;
    }>;
    pagination?: {
      page?: number;
      limit?: number;
      total?: number;
      totalPages?: number;
    };
  };
};

export type GetV2TasksResponse = GetV2TasksResponses[keyof GetV2TasksResponses];

export type PostV2TasksData = {
  body: {
    name: string;
    type:
      | "IMAGE_CLASSIFICATION"
      | "DATA_AGGREGATION"
      | "MODEL_INFERENCE"
      | "SENSOR_FUSION"
      | "VIDEO_PROCESSING"
      | "LOG_ANALYSIS"
      | "ANOMALY_DETECTION"
      | "DATA_PROCESSING"
      | "ETL_PIPELINE"
      | "ML_TRAINING"
      | "NLP"
      | "COMPUTER_VISION"
      | "SPEECH_RECOGNITION"
      | "RECOMMENDATION_ENGINE"
      | "FRAUD_DETECTION"
      | "IOT_DATA_INGESTION"
      | "REALTIME_ANALYTICS"
      | "BATCH_PROCESSING"
      | "CONTAINER_BUILD"
      | "CICD_PIPELINE"
      | "CUSTOM";
    priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
    target?: "EDGE" | "CLOUD" | "HYBRID";
    nodeId?: string;
    specs?: {
      cpuCores?: number;
      memoryGB?: number;
      memoryMB?: number;
    };
    input?: {
      [key: string]: unknown;
    };
    metadata?: {
      [key: string]: unknown;
    };
    maxRetries?: number;
    runtime?: "NATIVE" | "DOCKER" | "WASM";
    image: string;
    affinity?: string;
    traceId?: string;
  };
  path?: never;
  query?: never;
  url: "/v2/tasks/";
};

export type PostV2TasksErrors = {
  /**
   * Default Response
   */
  400: Def0;
  /**
   * Default Response
   */
  409: Def0;
};

export type PostV2TasksError = PostV2TasksErrors[keyof PostV2TasksErrors];

export type PostV2TasksResponses = {
  /**
   * Default Response
   */
  201: {
    id: string;
    name: string;
    type: string;
    status:
      | "PENDING"
      | "SCHEDULED"
      | "RUNNING"
      | "COMPLETED"
      | "FAILED"
      | "CANCELLED";
    priority: string;
    nodeId?: unknown | string | unknown;
    specs?:
      | unknown
      | {
          cpuCores: number;
          memoryGB: number;
        }
      | unknown;
    submittedAt: Date;
    startedAt?: unknown | Date | unknown;
    completedAt?: unknown | Date | unknown;
    error?: unknown | string | unknown;
    metadata?: {
      [key: string]: unknown;
    };
    runtime: "NATIVE" | "DOCKER" | "WASM";
    image: string;
    affinity?: unknown | string | unknown;
    traceId?: unknown | string | unknown;
  };
};

export type PostV2TasksResponse =
  PostV2TasksResponses[keyof PostV2TasksResponses];

export type GetV2TasksStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/tasks/stats";
};

export type GetV2TasksStatsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2TasksByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/tasks/{id}";
};

export type GetV2TasksByIdErrors = {
  /**
   * Default Response
   */
  404: Def0;
};

export type GetV2TasksByIdError =
  GetV2TasksByIdErrors[keyof GetV2TasksByIdErrors];

export type GetV2TasksByIdResponses = {
  /**
   * Default Response
   */
  200: {
    id: string;
    name: string;
    type: string;
    status:
      | "PENDING"
      | "SCHEDULED"
      | "RUNNING"
      | "COMPLETED"
      | "FAILED"
      | "CANCELLED";
    priority: string;
    nodeId?: unknown | string | unknown;
    specs?:
      | unknown
      | {
          cpuCores: number;
          memoryGB: number;
        }
      | unknown;
    submittedAt: Date;
    startedAt?: unknown | Date | unknown;
    completedAt?: unknown | Date | unknown;
    error?: unknown | string | unknown;
    metadata?: {
      [key: string]: unknown;
    };
    runtime: "NATIVE" | "DOCKER" | "WASM";
    image: string;
    affinity?: unknown | string | unknown;
    traceId?: unknown | string | unknown;
  };
};

export type GetV2TasksByIdResponse =
  GetV2TasksByIdResponses[keyof GetV2TasksByIdResponses];

export type PostV2TasksByIdCancelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/tasks/{id}/cancel";
};

export type PostV2TasksByIdCancelResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2TasksByIdLogsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    level?: string;
    limit?: number;
  };
  url: "/v2/tasks/{id}/logs";
};

export type GetV2TasksByIdLogsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2TasksByIdRetryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/tasks/{id}/retry";
};

export type PostV2TasksByIdRetryResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2TasksByIdSchedulingDecisionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/tasks/{id}/scheduling-decision";
};

export type GetV2TasksByIdSchedulingDecisionResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2WebhooksData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/webhooks/";
};

export type GetV2WebhooksResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2WebhooksData = {
  body: {
    name: string;
    url: string;
    events: Array<string>;
    secret?: string;
    enabled?: boolean;
  };
  path?: never;
  query?: never;
  url: "/v2/webhooks/";
};

export type PostV2WebhooksResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2WebhooksDeliveriesByIdRetryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/webhooks/deliveries/{id}/retry";
};

export type PostV2WebhooksDeliveriesByIdRetryResponses = {
  /**
   * Default Response
   */
  200: {
    success?: boolean;
    message?: string;
  };
};

export type PostV2WebhooksDeliveriesByIdRetryResponse =
  PostV2WebhooksDeliveriesByIdRetryResponses[keyof PostV2WebhooksDeliveriesByIdRetryResponses];

export type GetV2WebhooksStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/webhooks/stats";
};

export type GetV2WebhooksStatsResponses = {
  /**
   * Default Response
   */
  200: {
    total?: number;
    active?: number;
    failedLast24h?: number;
    avgLatency?: number;
  };
};

export type GetV2WebhooksStatsResponse =
  GetV2WebhooksStatsResponses[keyof GetV2WebhooksStatsResponses];

export type DeleteV2WebhooksByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/webhooks/{id}";
};

export type DeleteV2WebhooksByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PatchV2WebhooksByIdData = {
  body?: {
    name?: string;
    url?: string;
    events?: Array<string>;
    secret?: string;
    enabled?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/webhooks/{id}";
};

export type PatchV2WebhooksByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2WebhooksByIdDeliveriesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    limit?: number;
  };
  url: "/v2/webhooks/{id}/deliveries";
};

export type GetV2WebhooksByIdDeliveriesResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2WebhooksByIdRedeliverByDeliveryIdData = {
  body?: never;
  path: {
    id: string;
    deliveryId: string;
  };
  query?: never;
  url: "/v2/webhooks/{id}/redeliver/{deliveryId}";
};

export type PostV2WebhooksByIdRedeliverByDeliveryIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2WebhooksByIdTestData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/webhooks/{id}/test";
};

export type PostV2WebhooksByIdTestResponses = {
  /**
   * Default Response
   */
  200: {
    success?: boolean;
    deliveryId?: string;
  };
};

export type PostV2WebhooksByIdTestResponse =
  PostV2WebhooksByIdTestResponses[keyof PostV2WebhooksByIdTestResponses];

export type GetV2WorkflowsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v2/workflows/";
};

export type GetV2WorkflowsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2WorkflowsData = {
  body: {
    name: string;
    version: string;
    nodes: Array<{
      id: string;
      name: string;
      type: "task" | "decision" | "parallel" | "wait" | "subworkflow";
      config: {
        [key: string]: unknown;
      };
      inputs: Array<string>;
      outputs: Array<string>;
    }>;
    edges: Array<{
      id: string;
      from: string;
      to: string;
      condition?: string;
    }>;
    variables?: {
      [key: string]: unknown;
    };
    timeout?: number;
    retryPolicy?: {
      maxRetries?: number;
      initialDelay?: number;
      maxDelay?: number;
      multiplier?: number;
    };
  };
  path?: never;
  query?: never;
  url: "/v2/workflows/";
};

export type PostV2WorkflowsResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2WorkflowsExecutionsByExecutionIdData = {
  body?: never;
  path: {
    executionId: string;
  };
  query?: never;
  url: "/v2/workflows/executions/{executionId}";
};

export type GetV2WorkflowsExecutionsByExecutionIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type GetV2WorkflowsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/workflows/{id}";
};

export type GetV2WorkflowsByIdResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type PostV2WorkflowsByIdExecuteData = {
  body?: {
    input?: {
      [key: string]: unknown;
    };
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/v2/workflows/{id}/execute";
};

export type PostV2WorkflowsByIdExecuteResponses = {
  /**
   * Default Response
   */
  200: unknown;
};
