// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * ErrorSchema
 */
export const zDef0 = z.object({
  code: z.string(),
  message: z.string(),
  requestId: z.string(),
  timestamp: z.string().datetime(),
  details: z.unknown().optional(),
  stack: z.string().optional(),
});

/**
 * HealthSchema
 */
export const zDef1 = z.object({
  status: z.enum(["healthy", "degraded", "unhealthy"]),
  service: z.string(),
  timestamp: z.string().datetime(),
  checks: z.record(z.boolean()).optional(),
  version: z.string().optional(),
});

export const zGetV2AdminAuditLogsQuery = z.object({
  userId: z.string().optional(),
  action: z.string().optional(),
  limit: z.number().optional().default(100),
});

export const zPostV2AdminCleanupBody = z.object({
  olderThanDays: z.number(),
  types: z.array(z.string()),
});

export const zGetV2AdminDlqEventsQuery = z.object({
  topic: z.string().optional(),
  status: z
    .enum(["PENDING", "RETRYING", "REPROCESSED", "PERMANENTLY_FAILED"])
    .optional(),
  limit: z.number().optional().default(50),
  offset: z.number().optional().default(0),
});

export const zPostV2AdminDlqEventsByIdRetryPath = z.object({
  id: z.string(),
});

export const zPostV2AdminDlqPurgeBody = z.object({
  olderThanDays: z.number().optional().default(7),
});

export const zPostV2AdminUsersByIdDeactivatePath = z.object({
  id: z.string(),
});

export const zPatchV2AdminUsersByIdRoleBody = z.object({
  role: z.enum(["ADMIN", "OPERATOR", "VIEWER"]),
});

export const zPatchV2AdminUsersByIdRolePath = z.object({
  id: z.string(),
});

/**
 * Default Response
 */
export const zGetV2AgentsCaResponse = z.object({
  certificate: z.string().optional(),
});

export const zPostV2AgentsCertificatesSignBody = z.object({
  csr: z.string(),
  bootstrapToken: z.string(),
  nodeName: z.string(),
  region: z.string(),
  ipAddress: z.string().optional(),
  port: z.number().optional(),
  cpuCores: z.number().optional(),
  memoryGB: z.number().optional(),
  storageGB: z.number().optional(),
  hardwareId: z.string().optional(),
});

/**
 * Default Response
 */
export const zPostV2AgentsCertificatesSignResponse = z.object({
  certificate: z.string().optional(),
  caCertificate: z.string().optional(),
  nodeId: z.string().optional(),
  expiresAt: z.string().datetime().optional(),
});

export const zPostV2AgentsHeartbeatBody = z.object({
  timestamp: z.number().optional(),
  status: z.string().optional(),
  metrics: z
    .object({
      cpu_usage: z.number().optional(),
      memory_usage: z.number().optional(),
    })
    .optional(),
});

/**
 * Default Response
 */
export const zGetV2AgentsTasksPendingResponse = z.object({
  task_id: z.string().optional(),
  runtime: z.string().optional(),
  image: z.string().optional(),
  input: z.record(z.unknown()).optional(),
  memory_limit_mb: z.number().optional(),
  cpu_fuel: z.number().nullish(),
  timeout_seconds: z.number().optional(),
});

export const zPostV2AgentsTasksByTaskIdResultBody = z.object({
  status: z.string(),
  exit_code: z.number(),
  stdout: z.string().optional(),
  stderr: z.string().optional(),
  duration_ms: z.number().optional(),
  error: z.string().nullish(),
});

export const zPostV2AgentsTasksByTaskIdResultPath = z.object({
  taskId: z.string(),
});

export const zGetV2AlertsQuery = z.object({
  severity: z.enum(["critical", "warning", "info"]).optional(),
});

export const zPostV2AlertsTestBody = z.object({
  severity: z.enum(["critical", "warning", "info"]),
  title: z.string(),
  message: z.string(),
});

export const zPostV2AuthLoginBody = z.object({
  email: z.string().email(),
  password: z.string().min(1),
});

/**
 * Default Response
 */
export const zPostV2AuthLogoutResponse = z.object({
  success: z.boolean().optional(),
});

/**
 * Default Response
 */
export const zGetV2AuthMeResponse = z.object({
  id: z.string().optional(),
  email: z.string().optional(),
  name: z.string().optional(),
  role: z.string().optional(),
  createdAt: z.string().optional(),
  lastLoginAt: z.string().nullish(),
});

export const zPostV2AuthRefreshBody = z.object({
  refreshToken: z.string().min(1),
});

export const zPostV2AuthRegisterBody = z.object({
  email: z.string().email(),
  password: z.intersection(z.unknown(), z.unknown(), z.unknown()),
  name: z.string().min(2).max(100),
});

export const zGetV2CarbonMetricsQuery = z.object({
  region: z.string().optional(),
  from: z.string().datetime().optional(),
  to: z.string().datetime().optional(),
  granularity: z
    .enum(["hour", "day", "week", "month"])
    .optional()
    .default("day"),
});

export const zPostV2CarbonRecordBody = z.object({
  nodeId: z.string().optional(),
  region: z.string(),
  energyKwh: z.number(),
  carbonKg: z.number(),
  renewablePercent: z.number().optional(),
});

export const zGetV2CostRecordsQuery = z.object({
  nodeId: z.string().uuid().optional(),
  resourceType: z.string().optional(),
  from: z.string().datetime().optional(),
  to: z.string().datetime().optional(),
  granularity: z
    .enum(["hour", "day", "week", "month"])
    .optional()
    .default("day"),
});

export const zPostV2FlModelsBody = z.object({
  name: z.string().min(1).max(200),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  architecture: z.string().min(1),
  parameters: z.number().int().gte(1),
  weightsUrl: z.string().url().optional(),
  weightsSize: z.number().int().gte(0).optional(),
});

export const zGetV2FlModelsByIdPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2FlModelsByIdWeightsPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2FlModelsByIdWeightsPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2FlSessionsBody = z.object({
  modelId: z.string().uuid(),
  totalRounds: z.number().int().gte(1).lte(100).optional().default(10),
  config: z
    .object({
      minClients: z.number().int().gte(1).lte(100).optional().default(3),
      maxClients: z.number().int().gte(1).lte(1000).optional().default(10),
      localEpochs: z.number().int().gte(1).lte(100).optional().default(5),
      learningRate: z.number().gte(0.0001).lte(1).optional().default(0.01),
      aggregationStrategy: z
        .enum(["fedavg", "fedprox", "fedadam"])
        .optional()
        .default("fedavg"),
      privacyBudget: z.number().gte(0).lte(10).optional(),
      noiseMultiplier: z.number().gte(0).lte(10).optional(),
      gradientClipNorm: z.number().gte(0).lte(100).optional(),
    })
    .optional(),
});

export const zGetV2FlSessionsByIdPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2FlSessionsByIdStopPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2LogsQuery = z.object({
  taskId: z.string().optional(),
  nodeId: z.string().optional(),
  level: z.enum(["DEBUG", "INFO", "WARN", "ERROR"]).optional(),
  limit: z.number().optional().default(100),
  offset: z.number().optional().default(0),
});

/**
 * Default Response
 */
export const zGetV2MetricsMlResponse = z.object({
  activeModels: z.number().optional(),
  trainingJobs: z.number().optional(),
  avgAccuracy: z.number().optional(),
  totalPredictions: z.number().optional(),
});

/**
 * Default Response
 */
export const zGetV2MetricsNetworkResponse = z.object({
  ingressGbps: z.number().optional(),
  egressGbps: z.number().optional(),
  avgLatency: z.number().optional(),
  packetLoss: z.number().optional(),
});

export const zGetV2NodesQuery = z.object({
  region: z.string().optional(),
  status: z.enum(["ONLINE", "OFFLINE", "DEGRADED", "MAINTENANCE"]).optional(),
  page: z.number().int().gte(1).optional().default(1),
  limit: z.number().int().gte(1).lte(100).optional().default(20),
  sortBy: z
    .enum(["name", "region", "status", "createdAt"])
    .optional()
    .default("createdAt"),
  sortOrder: z.enum(["asc", "desc"]).optional().default("desc"),
});

/**
 * Default Response
 */
export const zGetV2NodesResponse = z.object({
  data: z
    .array(
      z.object({
        id: z.string().uuid(),
        name: z.string(),
        location: z.string(),
        region: z.string(),
        status: z.enum(["ONLINE", "OFFLINE", "DEGRADED", "MAINTENANCE"]),
        ipAddress: z.string(),
        port: z.number(),
        specs: z.object({
          cpuCores: z.number(),
          memoryGB: z.number(),
          storageGB: z.number(),
        }),
        load: z
          .object({
            cpuUsage: z.number().optional(),
            memoryUsage: z.number().optional(),
            activeTasks: z.number(),
          })
          .optional(),
        lastHeartbeat: z.string().datetime(),
      }),
    )
    .optional(),
  pagination: z
    .object({
      page: z.number().optional(),
      limit: z.number().optional(),
      total: z.number().optional(),
      totalPages: z.number().optional(),
    })
    .optional(),
});

export const zPostV2NodesBody = z.object({
  name: z.string().min(1).max(100),
  location: z.string().min(1).max(200),
  region: z.string().min(1).max(50),
  ipAddress: z.string().ip(),
  port: z.number().int().gte(1).lte(65535),
  cpuCores: z.number().int().gte(1).lte(128),
  memoryGB: z.number().int().gte(1).lte(1024),
  storageGB: z.number().int().gte(1).lte(10000),
  costPerHour: z.number().gte(0).lte(100).optional(),
  maxTasks: z.number().int().gte(1).lte(1000).optional(),
  bandwidthInMbps: z.number().int().gte(1).optional(),
  bandwidthOutMbps: z.number().int().gte(1).optional(),
});

/**
 * Default Response
 */
export const zPostV2NodesResponse = z.object({
  id: z.string().uuid(),
  name: z.string(),
  location: z.string(),
  region: z.string(),
  status: z.enum(["ONLINE", "OFFLINE", "DEGRADED", "MAINTENANCE"]),
  ipAddress: z.string(),
  port: z.number(),
  specs: z.object({
    cpuCores: z.number(),
    memoryGB: z.number(),
    storageGB: z.number(),
  }),
  load: z
    .object({
      cpuUsage: z.number().optional(),
      memoryUsage: z.number().optional(),
      activeTasks: z.number(),
    })
    .optional(),
  lastHeartbeat: z.string().datetime(),
});

export const zDeleteV2NodesByIdPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2NodesByIdPath = z.object({
  id: z.string().uuid(),
});

/**
 * Default Response
 */
export const zGetV2NodesByIdResponse = z.object({
  id: z.string().uuid(),
  name: z.string(),
  location: z.string(),
  region: z.string(),
  status: z.enum(["ONLINE", "OFFLINE", "DEGRADED", "MAINTENANCE"]),
  ipAddress: z.string(),
  port: z.number(),
  specs: z.object({
    cpuCores: z.number(),
    memoryGB: z.number(),
    storageGB: z.number(),
  }),
  load: z
    .object({
      cpuUsage: z.number().optional(),
      memoryUsage: z.number().optional(),
      activeTasks: z.number(),
    })
    .optional(),
  lastHeartbeat: z.string().datetime(),
});

export const zPatchV2NodesByIdBody = z.object({
  name: z.string().min(1).max(100).optional(),
  location: z.string().min(1).max(200).optional(),
  region: z.string().min(1).max(50).optional(),
  cpuCores: z.number().int().gte(1).lte(128).optional(),
  memoryGB: z.number().int().gte(1).lte(1024).optional(),
  storageGB: z.number().int().gte(1).lte(10000).optional(),
  costPerHour: z.number().gte(0).lte(100).optional(),
  maxTasks: z.number().int().gte(1).lte(1000).optional(),
  isMaintenanceMode: z.boolean().optional(),
});

export const zPatchV2NodesByIdPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2NodesByIdDrainPath = z.object({
  id: z.string().uuid(),
});

/**
 * Default Response
 */
export const zPostV2NodesByIdDrainResponse = z.object({
  success: z.boolean().optional(),
  message: z.string().optional(),
});

export const zPostV2NodesByIdHeartbeatBody = z.object({
  cpuUsage: z.number(),
  memoryUsage: z.number(),
  storageUsage: z.number().optional(),
  latency: z.number().optional(),
  tasksRunning: z.number().optional(),
  networkIn: z.number().optional(),
  networkOut: z.number().optional(),
});

export const zPostV2NodesByIdHeartbeatPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2NodesByIdMaintenanceBody = z.object({
  enabled: z.boolean(),
});

export const zPostV2NodesByIdMaintenancePath = z.object({
  id: z.string().uuid(),
});

export const zGetV2NodesByIdMetricsPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2NodesByIdMetricsQuery = z.object({
  from: z.string().datetime().optional(),
  to: z.string().datetime().optional(),
  limit: z.number().optional().default(100),
});

export const zPostV2NodesByIdOfflinePath = z.object({
  id: z.string().uuid(),
});

/**
 * Default Response
 */
export const zPostV2NodesByIdOfflineResponse = z.object({
  success: z.boolean().optional(),
  message: z.string().optional(),
});

export const zGetV2NodesByIdSchedulingHistoryPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2NodesByIdSchedulingHistoryQuery = z.object({
  days: z.number().optional().default(7),
});

export const zPatchV2PoliciesActiveBody = z.object({
  policy: z.string(),
});

export const zPatchV2PoliciesThresholdsBody = z.object({
  cpu: z.number().gte(0).lte(100).optional(),
  memory: z.number().gte(0).lte(100).optional(),
  latency: z.number().gte(0).optional(),
});

/**
 * Default Response
 */
export const zGetV2SchedulerMetricsResponse = z.object({
  queueLength: z.number().optional(),
  avgSchedulingTime: z.number().optional(),
  throughput: z.number().optional(),
  efficiency: z.number().optional(),
});

export const zGetV2TasksQuery = z.object({
  status: z
    .enum([
      "PENDING",
      "SCHEDULED",
      "RUNNING",
      "COMPLETED",
      "FAILED",
      "CANCELLED",
    ])
    .optional(),
  type: z.string().optional(),
  nodeId: z.string().uuid().optional(),
  priority: z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"]).optional(),
  page: z.number().int().gte(1).optional().default(1),
  limit: z.number().int().gte(1).lte(100).optional().default(20),
  sortBy: z
    .enum([
      "submittedAt",
      "priority",
      "status",
      "duration",
      "createdAt",
      "updatedAt",
      "name",
    ])
    .optional()
    .default("submittedAt"),
  sortOrder: z.enum(["asc", "desc"]).optional().default("desc"),
  from: z.string().datetime().optional(),
  to: z.string().datetime().optional(),
});

/**
 * Default Response
 */
export const zGetV2TasksResponse = z.object({
  data: z
    .array(
      z.object({
        id: z.string().uuid(),
        name: z.string(),
        type: z.string(),
        status: z.enum([
          "PENDING",
          "SCHEDULED",
          "RUNNING",
          "COMPLETED",
          "FAILED",
          "CANCELLED",
        ]),
        priority: z.string(),
        nodeId: z
          .union([z.union([z.unknown(), z.string().uuid()]), z.unknown()])
          .optional(),
        specs: z
          .union([
            z.union([
              z.unknown(),
              z.object({
                cpuCores: z.number(),
                memoryGB: z.number(),
              }),
            ]),
            z.unknown(),
          ])
          .optional(),
        submittedAt: z.string().datetime(),
        startedAt: z
          .union([z.union([z.unknown(), z.string().datetime()]), z.unknown()])
          .optional(),
        completedAt: z
          .union([z.union([z.unknown(), z.string().datetime()]), z.unknown()])
          .optional(),
        error: z
          .union([z.union([z.unknown(), z.string()]), z.unknown()])
          .optional(),
        metadata: z.record(z.unknown()).optional(),
        runtime: z.enum(["NATIVE", "DOCKER", "WASM"]),
        image: z.string(),
        affinity: z
          .union([z.union([z.unknown(), z.string()]), z.unknown()])
          .optional(),
        traceId: z
          .union([z.union([z.unknown(), z.string()]), z.unknown()])
          .optional(),
      }),
    )
    .optional(),
  pagination: z
    .object({
      page: z.number().optional(),
      limit: z.number().optional(),
      total: z.number().optional(),
      totalPages: z.number().optional(),
    })
    .optional(),
});

export const zPostV2TasksBody = z.object({
  name: z.string().min(1).max(200),
  type: z.enum([
    "IMAGE_CLASSIFICATION",
    "DATA_AGGREGATION",
    "MODEL_INFERENCE",
    "SENSOR_FUSION",
    "VIDEO_PROCESSING",
    "LOG_ANALYSIS",
    "ANOMALY_DETECTION",
    "DATA_PROCESSING",
    "ETL_PIPELINE",
    "ML_TRAINING",
    "NLP",
    "COMPUTER_VISION",
    "SPEECH_RECOGNITION",
    "RECOMMENDATION_ENGINE",
    "FRAUD_DETECTION",
    "IOT_DATA_INGESTION",
    "REALTIME_ANALYTICS",
    "BATCH_PROCESSING",
    "CONTAINER_BUILD",
    "CICD_PIPELINE",
    "CUSTOM",
  ]),
  priority: z
    .enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"])
    .optional()
    .default("MEDIUM"),
  target: z.enum(["EDGE", "CLOUD", "HYBRID"]).optional().default("EDGE"),
  nodeId: z.string().uuid().optional(),
  specs: z
    .object({
      cpuCores: z.number().int().gte(1).lte(128).optional(),
      memoryGB: z.number().int().gte(1).lte(1024).optional(),
      memoryMB: z.number().int().gte(1).lte(262144).optional(),
    })
    .optional(),
  input: z.record(z.unknown()).optional(),
  metadata: z.record(z.unknown()).optional(),
  maxRetries: z.number().int().gte(0).lte(10).optional().default(3),
  runtime: z.enum(["NATIVE", "DOCKER", "WASM"]).optional().default("DOCKER"),
  image: z.string().min(1),
  affinity: z.string().optional(),
  traceId: z.string().optional(),
});

/**
 * Default Response
 */
export const zPostV2TasksResponse = z.object({
  id: z.string().uuid(),
  name: z.string(),
  type: z.string(),
  status: z.enum([
    "PENDING",
    "SCHEDULED",
    "RUNNING",
    "COMPLETED",
    "FAILED",
    "CANCELLED",
  ]),
  priority: z.string(),
  nodeId: z
    .union([z.union([z.unknown(), z.string().uuid()]), z.unknown()])
    .optional(),
  specs: z
    .union([
      z.union([
        z.unknown(),
        z.object({
          cpuCores: z.number(),
          memoryGB: z.number(),
        }),
      ]),
      z.unknown(),
    ])
    .optional(),
  submittedAt: z.string().datetime(),
  startedAt: z
    .union([z.union([z.unknown(), z.string().datetime()]), z.unknown()])
    .optional(),
  completedAt: z
    .union([z.union([z.unknown(), z.string().datetime()]), z.unknown()])
    .optional(),
  error: z.union([z.union([z.unknown(), z.string()]), z.unknown()]).optional(),
  metadata: z.record(z.unknown()).optional(),
  runtime: z.enum(["NATIVE", "DOCKER", "WASM"]),
  image: z.string(),
  affinity: z
    .union([z.union([z.unknown(), z.string()]), z.unknown()])
    .optional(),
  traceId: z
    .union([z.union([z.unknown(), z.string()]), z.unknown()])
    .optional(),
});

export const zGetV2TasksByIdPath = z.object({
  id: z.string().uuid(),
});

/**
 * Default Response
 */
export const zGetV2TasksByIdResponse = z.object({
  id: z.string().uuid(),
  name: z.string(),
  type: z.string(),
  status: z.enum([
    "PENDING",
    "SCHEDULED",
    "RUNNING",
    "COMPLETED",
    "FAILED",
    "CANCELLED",
  ]),
  priority: z.string(),
  nodeId: z
    .union([z.union([z.unknown(), z.string().uuid()]), z.unknown()])
    .optional(),
  specs: z
    .union([
      z.union([
        z.unknown(),
        z.object({
          cpuCores: z.number(),
          memoryGB: z.number(),
        }),
      ]),
      z.unknown(),
    ])
    .optional(),
  submittedAt: z.string().datetime(),
  startedAt: z
    .union([z.union([z.unknown(), z.string().datetime()]), z.unknown()])
    .optional(),
  completedAt: z
    .union([z.union([z.unknown(), z.string().datetime()]), z.unknown()])
    .optional(),
  error: z.union([z.union([z.unknown(), z.string()]), z.unknown()]).optional(),
  metadata: z.record(z.unknown()).optional(),
  runtime: z.enum(["NATIVE", "DOCKER", "WASM"]),
  image: z.string(),
  affinity: z
    .union([z.union([z.unknown(), z.string()]), z.unknown()])
    .optional(),
  traceId: z
    .union([z.union([z.unknown(), z.string()]), z.unknown()])
    .optional(),
});

export const zPostV2TasksByIdCancelPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2TasksByIdLogsPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2TasksByIdLogsQuery = z.object({
  level: z.string().optional(),
  limit: z.number().optional().default(100),
});

export const zPostV2TasksByIdRetryPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2TasksByIdSchedulingDecisionPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2WebhooksBody = z.object({
  name: z.string().min(1).max(100),
  url: z.string().url(),
  events: z.array(z.string()).min(1),
  secret: z.string().min(16).max(100).optional(),
  enabled: z.boolean().optional().default(true),
});

export const zPostV2WebhooksDeliveriesByIdRetryPath = z.object({
  id: z.string().uuid(),
});

/**
 * Default Response
 */
export const zPostV2WebhooksDeliveriesByIdRetryResponse = z.object({
  success: z.boolean().optional(),
  message: z.string().optional(),
});

/**
 * Default Response
 */
export const zGetV2WebhooksStatsResponse = z.object({
  total: z.number().optional(),
  active: z.number().optional(),
  failedLast24h: z.number().optional(),
  avgLatency: z.number().optional(),
});

export const zDeleteV2WebhooksByIdPath = z.object({
  id: z.string().uuid(),
});

export const zPatchV2WebhooksByIdBody = z.object({
  name: z.string().min(1).max(100).optional(),
  url: z.string().url().optional(),
  events: z.array(z.string()).min(1).optional(),
  secret: z.string().min(16).max(100).optional(),
  enabled: z.boolean().optional(),
});

export const zPatchV2WebhooksByIdPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2WebhooksByIdDeliveriesPath = z.object({
  id: z.string().uuid(),
});

export const zGetV2WebhooksByIdDeliveriesQuery = z.object({
  limit: z.number().optional().default(50),
});

export const zPostV2WebhooksByIdRedeliverByDeliveryIdPath = z.object({
  id: z.string(),
  deliveryId: z.string(),
});

export const zPostV2WebhooksByIdTestPath = z.object({
  id: z.string().uuid(),
});

/**
 * Default Response
 */
export const zPostV2WebhooksByIdTestResponse = z.object({
  success: z.boolean().optional(),
  deliveryId: z.string().optional(),
});

export const zPostV2WorkflowsBody = z.object({
  name: z.string().min(1).max(200),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  nodes: z
    .array(
      z.object({
        id: z.string(),
        name: z.string(),
        type: z.enum(["task", "decision", "parallel", "wait", "subworkflow"]),
        config: z.record(z.unknown()),
        inputs: z.array(z.string()),
        outputs: z.array(z.string()),
      }),
    )
    .min(1),
  edges: z.array(
    z.object({
      id: z.string(),
      from: z.string(),
      to: z.string(),
      condition: z.string().optional(),
    }),
  ),
  variables: z.record(z.unknown()).optional(),
  timeout: z.number().int().gte(1000).lte(86400000).optional().default(60000),
  retryPolicy: z
    .object({
      maxRetries: z.number().int().gte(0).lte(10).optional().default(3),
      initialDelay: z.number().int().gte(100).optional().default(1000),
      maxDelay: z.number().int().gte(1000).optional().default(60000),
      multiplier: z.number().gte(1).optional().default(2),
    })
    .optional(),
});

export const zGetV2WorkflowsExecutionsByExecutionIdPath = z.object({
  executionId: z.string(),
});

export const zGetV2WorkflowsByIdPath = z.object({
  id: z.string().uuid(),
});

export const zPostV2WorkflowsByIdExecuteBody = z.object({
  input: z.record(z.unknown()).optional(),
});

export const zPostV2WorkflowsByIdExecutePath = z.object({
  id: z.string().uuid(),
});
