// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * ErrorSchema
 */
export const zDef0 = z.object({
    error: z.object({
        code: z.string(),
        details: z.unknown().optional(),
        message: z.string(),
        requestId: z.string().optional(),
        stack: z.string().optional(),
        timestamp: z.string().datetime().optional()
    })
});

/**
 * HealthSchema
 */
export const zDef1 = z.object({
    checks: z.record(z.boolean()).optional(),
    service: z.string(),
    status: z.enum([
        'degraded',
        'healthy',
        'unhealthy'
    ]),
    timestamp: z.string().datetime(),
    version: z.string().optional()
});

export const zGetV2AdminAuditLogsQuery = z.object({
    userId: z.string().optional(),
    action: z.string().optional(),
    limit: z.number().optional().default(100)
});

export const zPostV2AdminCleanupBody = z.object({
    olderThanDays: z.number().int().gte(1),
    types: z.array(z.string())
});

export const zGetV2AdminDlqEventsQuery = z.object({
    topic: z.string().optional(),
    status: z.enum([
        'PENDING',
        'PERMANENTLY_FAILED',
        'REPROCESSED',
        'RETRYING'
    ]).optional(),
    limit: z.number().int().gte(1).lte(100).optional(),
    offset: z.number().int().gte(0).optional()
});

export const zPostV2AdminDlqEventsByIdRetryPath = z.object({
    id: z.string().uuid()
});

export const zPostV2AdminDlqPurgeBody = z.object({
    olderThanDays: z.number().int().optional()
});

export const zPostV2AdminEventsRepublishBody = z.object({
    entityId: z.string(),
    eventType: z.string(),
    targetTopic: z.string().optional()
});

export const zPostV2AdminEventsRepublishRangeBody = z.object({
    dryRun: z.boolean().optional(),
    eventType: z.string(),
    fromTimestamp: z.string(),
    toTimestamp: z.string()
});

export const zPostV2AdminUsersByIdDeactivatePath = z.object({
    id: z.string().uuid()
});

export const zPatchV2AdminUsersByIdRoleBody = z.object({
    role: z.enum([
        'ADMIN',
        'OPERATOR',
        'SUPER_ADMIN',
        'VIEWER'
    ])
});

export const zPatchV2AdminUsersByIdRolePath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zGetV2AgentsCaResponse = z.object({
    certificate: z.string().optional()
});

export const zPostV2AgentsCertificatesSignBody = z.object({
    bootstrapToken: z.string(),
    cpuCores: z.number().optional(),
    csr: z.string(),
    hardwareId: z.string().optional(),
    ipAddress: z.string().optional(),
    memoryGB: z.number().optional(),
    nodeName: z.string(),
    port: z.number().optional(),
    region: z.string(),
    storageGB: z.number().optional()
});

/**
 * Default Response
 */
export const zPostV2AgentsCertificatesSignResponse = z.object({
    caCertificate: z.string().optional(),
    certificate: z.string().optional(),
    expiresAt: z.string().datetime().optional(),
    nodeId: z.string().optional()
});

export const zPostV2AgentsHeartbeatBody = z.object({
    metrics: z.object({
        cpu_usage: z.number().optional(),
        memory_usage: z.number().optional()
    }).optional(),
    status: z.string().optional(),
    timestamp: z.number().optional()
});

/**
 * Default Response
 */
export const zGetV2AgentsTasksPendingResponse = z.object({
    cpu_fuel: z.number().nullish(),
    image: z.string().optional(),
    input: z.record(z.unknown()).optional(),
    memory_limit_mb: z.number().optional(),
    runtime: z.string().optional(),
    task_id: z.string().optional(),
    timeout_seconds: z.number().optional(),
    wasm_artifact_id: z.string().nullish()
});

export const zPostV2AgentsTasksByTaskIdResultBody = z.object({
    duration_ms: z.number().optional(),
    error: z.string().nullish(),
    exit_code: z.number(),
    metrics: z.object({
        cpu_usage_avg: z.number().optional(),
        memory_usage_max: z.number().optional(),
        network_egress_bytes: z.number().optional(),
        network_ingress_bytes: z.number().optional()
    }).optional(),
    status: z.string(),
    stderr: z.string().optional(),
    stdout: z.string().optional()
});

export const zPostV2AgentsTasksByTaskIdResultPath = z.object({
    taskId: z.string()
});

export const zPostV2AgentsTasksByTaskIdStatusBody = z.object({
    status: z.string()
});

export const zPostV2AgentsTasksByTaskIdStatusPath = z.object({
    taskId: z.string()
});

/**
 * Default Response
 */
export const zGetV2AlertsResponse = z.object({
    alerts: z.array(z.object({
        acknowledgedAt: z.string().nullish(),
        description: z.string().optional(),
        firedAt: z.string().optional(),
        id: z.string().optional(),
        resolvedAt: z.string().nullish(),
        severity: z.enum([
            'CRITICAL',
            'HIGH',
            'LOW',
            'MEDIUM'
        ]).optional(),
        source: z.string().optional(),
        title: z.string().optional()
    })).optional()
});

export const zPostV2AlertsTestBody = z.object({
    description: z.string(),
    severity: z.enum([
        'CRITICAL',
        'HIGH',
        'LOW',
        'MEDIUM'
    ]),
    title: z.string()
});

export const zPostV2AlertsByIdAcknowledgePath = z.object({
    id: z.string()
});

export const zGetV2AnalyticsCostQuery = z.object({
    from: z.string().datetime().optional(),
    to: z.string().datetime().optional(),
    nodeId: z.string().uuid().optional()
});

/**
 * Default Response
 */
export const zGetV2AnalyticsCostResponse = z.object({
    costByNode: z.array(z.object({
        cost: z.number().optional(),
        nodeId: z.string().optional(),
        nodeName: z.string().optional(),
        taskCount: z.number().optional()
    })).optional(),
    costOverTime: z.array(z.object({
        cost: z.number().optional(),
        date: z.string().optional()
    })).optional(),
    totalActualCost: z.number().optional(),
    totalSavings: z.number().optional()
});

export const zPostV2ApiKeysBody = z.object({
    expiresAt: z.union([
        z.union([
            z.unknown(),
            z.string().datetime()
        ]),
        z.unknown()
    ]).optional(),
    name: z.string().min(1).max(100).regex(/^[a-zA-Z0-9\s\-_]+$/),
    permissions: z.array(z.string()).optional()
});

export const zDeleteV2ApiKeysByIdPath = z.object({
    id: z.string().uuid()
});

export const zPostV2AuthLoginBody = z.object({
    email: z.string().email(),
    password: z.string().min(1)
});

/**
 * Default Response
 */
export const zPostV2AuthLoginResponse = z.object({
    accessToken: z.string(),
    expiresAt: z.string().datetime(),
    refreshToken: z.string(),
    token: z.string(),
    user: z.object({
        email: z.string().email(),
        id: z.string().uuid(),
        name: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        role: z.string()
    })
});

/**
 * Default Response
 */
export const zPostV2AuthLogoutResponse = z.object({
    success: z.boolean().optional()
});

export const zPostV2AuthRefreshBody = z.object({
    refreshToken: z.string().min(1)
});

export const zPostV2AuthRegisterBody = z.object({
    email: z.string().email(),
    name: z.string().min(2).max(100).regex(/^[a-zA-Z\s\-\.]+$/),
    password: z.string().min(12).max(128)
});

/**
 * Default Response
 */
export const zPostV2AuthRegisterResponse = z.object({
    accessToken: z.string(),
    expiresAt: z.string().datetime(),
    refreshToken: z.string(),
    token: z.string(),
    user: z.object({
        email: z.string().email(),
        id: z.string().uuid(),
        name: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        role: z.string()
    })
});

export const zDeleteV2AuthSessionsByIdPath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zGetV2CarbonByRegionResponse = z.array(z.object({
    carbonIntensityGco2: z.number().optional(),
    lastUpdatedAt: z.string().optional(),
    source: z.string().optional(),
    zone: z.string().optional()
}));

/**
 * Default Response
 */
export const zGetV2CarbonIntensityResponse = z.object({
    regions: z.array(z.object({
        carbonIntensityGco2: z.number().optional(),
        lastUpdatedAt: z.string().optional(),
        source: z.string().optional(),
        zone: z.string().optional()
    })).optional()
});

/**
 * Default Response
 */
export const zGetV2CarbonPolicyResponse = z.object({
    activePolicy: z.string().optional(),
    carbonWeight: z.number().optional(),
    isActive: z.boolean().optional()
});

export const zPatchV2CarbonPolicyBody = z.object({
    carbonWeight: z.number().gte(0).lte(1)
});

/**
 * Default Response
 */
export const zPatchV2CarbonPolicyResponse = z.object({
    carbonWeight: z.number().optional(),
    success: z.boolean().optional()
});

export const zGetV2CarbonReportQuery = z.object({
    from: z.string().datetime().optional(),
    to: z.string().datetime().optional(),
    tenantId: z.string().uuid().optional(),
    format: z.enum(['csv', 'json']).optional().default('json')
});

export const zGetV2CarbonSavingsQuery = z.object({
    days: z.number().int().gte(1).lte(365).optional().default(7)
});

/**
 * Default Response
 */
export const zGetV2CarbonSavingsResponse = z.object({
    equivalentTreesPlanted: z.number().optional(),
    savingsHistory: z.array(z.object({
        date: z.string().optional(),
        savedGco2: z.number().optional()
    })).optional(),
    totalSavedGco2Today: z.number().optional(),
    totalSavedGco2Week: z.number().optional()
});

/**
 * Default Response
 */
export const zGetV2CarbonSummaryResponse = z.object({
    equivalentTreesPlanted: z.number().optional(),
    totalSavedGco2Today: z.number().optional(),
    totalSavedGco2Week: z.number().optional()
});

/**
 * Default Response
 */
export const zGetV2CircuitBreakersResponse = z.array(z.object({
    failureCount: z.number().optional(),
    failureRate: z.number().optional(),
    lastStateChange: z.string().optional(),
    name: z.string().optional(),
    nextRetryAt: z.string().optional(),
    state: z.enum([
        'CLOSED',
        'HALF_OPEN',
        'OPEN'
    ]).optional(),
    successCount: z.number().optional()
}));

export const zPostV2CircuitBreakersByNameResetPath = z.object({
    name: z.string().min(1)
});

/**
 * Default Response
 */
export const zPostV2CircuitBreakersByNameResetResponse = z.object({
    message: z.string().optional(),
    success: z.boolean().optional()
});

export const zGetV2CostRecordsQuery = z.object({
    nodeId: z.string().uuid().optional(),
    resourceType: z.string().optional(),
    from: z.string().datetime().optional(),
    to: z.string().datetime().optional(),
    granularity: z.enum([
        'day',
        'hour',
        'month',
        'week'
    ]).optional().default('day')
});

export const zPostV2FlModelsBody = z.object({
    architecture: z.string().min(1),
    name: z.string().min(1).max(200),
    parameters: z.number().int().gte(1),
    version: z.string().regex(/^\d+\.\d+\.\d+$/),
    weightsSize: z.number().int().gte(0).optional(),
    weightsUrl: z.string().url().optional()
});

export const zGetV2FlModelsByIdPath = z.object({
    id: z.string().uuid()
});

export const zGetV2FlModelsByIdWeightsPath = z.object({
    id: z.string().uuid()
});

export const zPostV2FlModelsByIdWeightsPath = z.object({
    id: z.string().uuid()
});

export const zPostV2FlSessionsBody = z.object({
    config: z.object({
        aggregationStrategy: z.enum([
            'fedadam',
            'fedavg',
            'fedprox'
        ]).optional().default('fedavg'),
        gradientClipNorm: z.number().gte(0).lte(100).optional(),
        learningRate: z.number().gte(0.0001).lte(1).optional().default(0.01),
        localEpochs: z.number().int().gte(1).lte(100).optional().default(5),
        maxClients: z.number().int().gte(1).lte(1000).optional().default(10),
        minClients: z.number().int().gte(1).lte(100).optional().default(3),
        noiseMultiplier: z.number().gte(0).lte(10).optional(),
        privacyBudget: z.number().gte(0).lte(10).optional()
    }).optional(),
    modelId: z.string().uuid(),
    totalRounds: z.number().int().gte(1).lte(100).optional().default(10)
});

export const zGetV2FlSessionsByIdPath = z.object({
    id: z.string().uuid()
});

export const zPostV2FlSessionsByIdStopPath = z.object({
    id: z.string().uuid()
});

export const zGetV2LogsQuery = z.object({
    taskId: z.string().optional(),
    nodeId: z.string().optional(),
    level: z.enum([
        'DEBUG',
        'ERROR',
        'INFO',
        'WARN'
    ]).optional(),
    limit: z.number().optional().default(100),
    offset: z.number().optional().default(0)
});

/**
 * Default Response
 */
export const zGetV2MetricsMlResponse = z.object({
    activeModels: z.number().optional(),
    avgAccuracy: z.number().optional(),
    totalPredictions: z.number().optional(),
    trainingJobs: z.number().optional()
});

/**
 * Default Response
 */
export const zGetV2MetricsNetworkResponse = z.object({
    avgLatency: z.number().optional(),
    egressGbps: z.number().optional(),
    ingressGbps: z.number().optional(),
    packetLoss: z.number().optional()
});

/**
 * Default Response
 */
export const zGetV2MlDriftCurrentResponse = z.object({
    driftScore: z.number().optional(),
    featureDrift: z.record(z.number()).optional(),
    isDrifting: z.boolean().optional(),
    lastCheckedAt: z.string().optional()
});

export const zGetV2MlDriftHistoryQuery = z.object({
    hours: z.number().int().gte(1).lte(720).optional().default(24)
});

/**
 * Default Response
 */
export const zGetV2MlDriftHistoryResponse = z.array(z.object({
    score: z.number().optional(),
    timestamp: z.string().optional()
}));

export const zGetV2MlFederatedModelByModelIdWeightsPath = z.object({
    modelId: z.string()
});

/**
 * Default Response
 */
export const zGetV2MlFederatedRoundResponse = z.object({
    minParticipants: z.number().optional(),
    modelId: z.string().optional(),
    roundId: z.string().optional(),
    roundNumber: z.number().optional(),
    status: z.string().optional(),
    submissionsCount: z.number().optional()
});

export const zPostV2MlFederatedWeightsBody = z.object({
    avgReward: z.number().nullish(),
    nodeId: z.string(),
    roundId: z.string(),
    sampleCount: z.number(),
    weightsUrl: z.string()
});

/**
 * Default Response
 */
export const zPostV2MlFederatedWeightsResponse = z.object({
    message: z.string().optional(),
    success: z.boolean().optional()
});

/**
 * Default Response
 */
export const zGetV2MlModelCurrentResponse = z.object({
    accuracy: z.number().optional(),
    fallbackRate: z.number().optional(),
    lastUpdatedAt: z.string().optional(),
    modelType: z.string().optional(),
    trainedAt: z.string().optional(),
    version: z.string().optional()
});

/**
 * Default Response
 */
export const zGetV2MlOutcomesStatsResponse = z.object({
    banditExplorationRate: z.number().optional(),
    nextUpdateAt: z.number().optional(),
    outcomesBuffered: z.number().optional(),
    predictionErrorP99Ms: z.number().optional()
});

/**
 * Default Response
 */
export const zPostV2MlRetrainResponse = z.object({
    message: z.string().optional(),
    success: z.boolean().optional()
});

/**
 * Default Response
 */
export const zGetV2MlRetrainStatusResponse = z.object({
    error: z.string().nullish(),
    lastStartedAt: z.string().optional(),
    status: z.string().optional()
});

export const zGetV2NodesQuery = z.object({
    region: z.string().optional(),
    status: z.enum([
        'DEGRADED',
        'MAINTENANCE',
        'OFFLINE',
        'ONLINE'
    ]).optional(),
    page: z.number().int().gte(1).optional().default(1),
    limit: z.number().int().gte(1).lte(100).optional().default(20),
    sortBy: z.enum([
        'createdAt',
        'name',
        'region',
        'status'
    ]).optional().default('createdAt'),
    sortOrder: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Default Response
 */
export const zGetV2NodesResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        ipAddress: z.string(),
        lastHeartbeat: z.string().datetime(),
        load: z.object({
            activeTasks: z.number(),
            cpuUsage: z.number().optional(),
            memoryUsage: z.number().optional()
        }).optional(),
        location: z.string(),
        name: z.string(),
        port: z.number(),
        region: z.string(),
        specs: z.object({
            cpuCores: z.number(),
            memoryGB: z.number(),
            storageGB: z.number()
        }),
        status: z.enum([
            'DEGRADED',
            'MAINTENANCE',
            'OFFLINE',
            'ONLINE'
        ])
    })).optional(),
    pagination: z.object({
        limit: z.number().optional(),
        page: z.number().optional(),
        total: z.number().optional(),
        totalPages: z.number().optional()
    }).optional()
});

export const zPostV2NodesBody = z.object({
    bandwidthInMbps: z.number().int().gte(1).optional(),
    bandwidthOutMbps: z.number().int().gte(1).optional(),
    costPerHour: z.number().gte(0).lte(100).optional(),
    cpuCores: z.number().int().gte(1).lte(128),
    ipAddress: z.string().ip(),
    location: z.string().min(1).max(200),
    maxTasks: z.number().int().gte(1).lte(1000).optional(),
    memoryGB: z.number().int().gte(1).lte(1024),
    name: z.string().min(1).max(100),
    port: z.number().int().gte(1).lte(65535),
    region: z.string().min(1).max(50),
    storageGB: z.number().int().gte(1).lte(10000)
});

/**
 * Default Response
 */
export const zPostV2NodesResponse = z.object({
    id: z.string(),
    ipAddress: z.string(),
    lastHeartbeat: z.string().datetime(),
    load: z.object({
        activeTasks: z.number(),
        cpuUsage: z.number().optional(),
        memoryUsage: z.number().optional()
    }).optional(),
    location: z.string(),
    name: z.string(),
    port: z.number(),
    region: z.string(),
    specs: z.object({
        cpuCores: z.number(),
        memoryGB: z.number(),
        storageGB: z.number()
    }),
    status: z.enum([
        'DEGRADED',
        'MAINTENANCE',
        'OFFLINE',
        'ONLINE'
    ])
});

export const zDeleteV2NodesByIdPath = z.object({
    id: z.string().uuid()
});

export const zGetV2NodesByIdPath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zGetV2NodesByIdResponse = z.object({
    id: z.string(),
    ipAddress: z.string(),
    lastHeartbeat: z.string().datetime(),
    load: z.object({
        activeTasks: z.number(),
        cpuUsage: z.number().optional(),
        memoryUsage: z.number().optional()
    }).optional(),
    location: z.string(),
    name: z.string(),
    port: z.number(),
    region: z.string(),
    specs: z.object({
        cpuCores: z.number(),
        memoryGB: z.number(),
        storageGB: z.number()
    }),
    status: z.enum([
        'DEGRADED',
        'MAINTENANCE',
        'OFFLINE',
        'ONLINE'
    ])
});

export const zPatchV2NodesByIdBody = z.object({
    costPerHour: z.number().gte(0).lte(100).optional(),
    cpuCores: z.number().int().gte(1).lte(128).optional(),
    isMaintenanceMode: z.boolean().optional(),
    location: z.string().min(1).max(200).optional(),
    maxTasks: z.number().int().gte(1).lte(1000).optional(),
    memoryGB: z.number().int().gte(1).lte(1024).optional(),
    name: z.string().min(1).max(100).optional(),
    region: z.string().min(1).max(50).optional(),
    storageGB: z.number().int().gte(1).lte(10000).optional()
});

export const zPatchV2NodesByIdPath = z.object({
    id: z.string().uuid()
});

export const zPostV2NodesByIdDrainPath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zPostV2NodesByIdDrainResponse = z.object({
    message: z.string().optional(),
    success: z.boolean().optional()
});

export const zPostV2NodesByIdHeartbeatBody = z.object({
    cpuUsage: z.number(),
    latency: z.number().optional(),
    memoryUsage: z.number(),
    networkIn: z.number().optional(),
    networkOut: z.number().optional(),
    storageUsage: z.number().optional(),
    tasksRunning: z.number().optional()
});

export const zPostV2NodesByIdHeartbeatPath = z.object({
    id: z.string().uuid()
});

export const zPostV2NodesByIdMaintenanceBody = z.object({
    enabled: z.boolean()
});

export const zPostV2NodesByIdMaintenancePath = z.object({
    id: z.string().uuid()
});

export const zGetV2NodesByIdMetricsPath = z.object({
    id: z.string().uuid()
});

export const zGetV2NodesByIdMetricsQuery = z.object({
    from: z.string().datetime().optional(),
    to: z.string().datetime().optional(),
    limit: z.number().optional().default(100)
});

export const zPostV2NodesByIdOfflinePath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zPostV2NodesByIdOfflineResponse = z.object({
    message: z.string().optional(),
    success: z.boolean().optional()
});

export const zGetV2NodesByIdSchedulingHistoryPath = z.object({
    id: z.string().uuid()
});

export const zGetV2NodesByIdSchedulingHistoryQuery = z.object({
    days: z.number().optional().default(7)
});

export const zPatchV2PoliciesActiveBody = z.object({
    policy: z.string()
});

export const zPatchV2PoliciesThresholdsBody = z.object({
    cpu: z.number().gte(0).lte(100).optional(),
    latency: z.number().gte(0).optional(),
    memory: z.number().gte(0).lte(100).optional()
});

export const zGetV2SchedulerDecisionsQuery = z.object({
    nodeId: z.string().uuid().optional(),
    limit: z.number().int().gte(1).lte(500).optional().default(50)
});

/**
 * Default Response
 */
export const zGetV2SchedulerMetricsResponse = z.object({
    avgSchedulingTime: z.number().optional(),
    efficiency: z.number().optional(),
    queueLength: z.number().optional(),
    throughput: z.number().optional()
});

export const zPutV2SchedulingPolicyBody = z.object({
    carbonWeight: z.number().gte(0).lte(1),
    costWeight: z.number().gte(0).lte(1),
    latencyWeight: z.number().gte(0).lte(1)
});

export const zGetV2TasksQuery = z.object({
    status: z.enum([
        'CANCELLED',
        'COMPLETED',
        'FAILED',
        'PENDING',
        'RUNNING',
        'SCHEDULED'
    ]).optional(),
    type: z.string().optional(),
    nodeId: z.string().optional(),
    priority: z.enum([
        'CRITICAL',
        'HIGH',
        'LOW',
        'MEDIUM'
    ]).optional(),
    page: z.number().int().gte(1).optional().default(1),
    limit: z.number().int().gte(1).lte(10000).optional().default(20),
    sortBy: z.enum([
        'createdAt',
        'duration',
        'name',
        'priority',
        'status',
        'submittedAt',
        'updatedAt'
    ]).optional().default('submittedAt'),
    sortOrder: z.enum(['asc', 'desc']).optional().default('desc'),
    from: z.string().datetime().optional(),
    to: z.string().datetime().optional()
});

/**
 * Default Response
 */
export const zGetV2TasksResponse = z.object({
    data: z.array(z.object({
        affinity: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        completedAt: z.union([
            z.union([
                z.unknown(),
                z.string().datetime()
            ]),
            z.unknown()
        ]).optional(),
        error: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        id: z.string().uuid(),
        image: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        metadata: z.record(z.unknown()).optional(),
        name: z.string(),
        nodeId: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        priority: z.string(),
        runtime: z.enum([
            'DOCKER',
            'NATIVE',
            'WASM'
        ]),
        specs: z.union([
            z.union([
                z.unknown(),
                z.object({
                    cpuCores: z.number(),
                    memoryGB: z.number()
                })
            ]),
            z.unknown()
        ]).optional(),
        startedAt: z.union([
            z.union([
                z.unknown(),
                z.string().datetime()
            ]),
            z.unknown()
        ]).optional(),
        status: z.enum([
            'CANCELLED',
            'COMPLETED',
            'FAILED',
            'PENDING',
            'RUNNING',
            'SCHEDULED'
        ]),
        submittedAt: z.string().datetime(),
        traceId: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional(),
        type: z.string(),
        wasmArtifactId: z.union([
            z.union([
                z.unknown(),
                z.string()
            ]),
            z.unknown()
        ]).optional()
    })).optional(),
    pagination: z.object({
        limit: z.number().optional(),
        page: z.number().optional(),
        total: z.number().optional(),
        totalPages: z.number().optional()
    }).optional()
});

export const zPostV2TasksBody = z.object({
    affinity: z.string().optional(),
    image: z.string().optional(),
    input: z.record(z.unknown()).optional(),
    isDeferrable: z.boolean().optional(),
    maxDelayMinutes: z.number().int().gte(0).optional(),
    maxRetries: z.number().int().gte(0).lte(10).optional().default(3),
    metadata: z.record(z.unknown()).optional(),
    name: z.string().min(1).max(200),
    nodeId: z.string().optional(),
    policy: z.string().optional(),
    priority: z.enum([
        'CRITICAL',
        'HIGH',
        'LOW',
        'MEDIUM'
    ]).optional().default('MEDIUM'),
    runtime: z.enum([
        'DOCKER',
        'NATIVE',
        'WASM'
    ]).optional().default('DOCKER'),
    specs: z.object({
        cpuCores: z.number().int().gte(1).lte(128).optional(),
        memoryGB: z.number().int().gte(1).lte(1024).optional(),
        memoryMB: z.number().int().gte(1).lte(262144).optional()
    }).optional(),
    target: z.enum([
        'CLOUD',
        'EDGE',
        'HYBRID'
    ]).optional().default('EDGE'),
    traceId: z.string().optional(),
    type: z.enum([
        'ANOMALY_DETECTION',
        'BATCH_PROCESSING',
        'CICD_PIPELINE',
        'COMPUTER_VISION',
        'CONTAINER_BUILD',
        'CUSTOM',
        'DATA_AGGREGATION',
        'DATA_PROCESSING',
        'ETL_PIPELINE',
        'FRAUD_DETECTION',
        'IMAGE_CLASSIFICATION',
        'IOT_DATA_INGESTION',
        'LOG_ANALYSIS',
        'ML_TRAINING',
        'MODEL_INFERENCE',
        'NLP',
        'REALTIME_ANALYTICS',
        'RECOMMENDATION_ENGINE',
        'SENSOR_FUSION',
        'SPEECH_RECOGNITION',
        'VIDEO_PROCESSING'
    ]),
    wasmArtifactId: z.string().optional()
});

/**
 * Default Response
 */
export const zPostV2TasksResponse = z.object({
    affinity: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    completedAt: z.union([
        z.union([
            z.unknown(),
            z.string().datetime()
        ]),
        z.unknown()
    ]).optional(),
    error: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    id: z.string().uuid(),
    image: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    metadata: z.record(z.unknown()).optional(),
    name: z.string(),
    nodeId: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    priority: z.string(),
    runtime: z.enum([
        'DOCKER',
        'NATIVE',
        'WASM'
    ]),
    specs: z.union([
        z.union([
            z.unknown(),
            z.object({
                cpuCores: z.number(),
                memoryGB: z.number()
            })
        ]),
        z.unknown()
    ]).optional(),
    startedAt: z.union([
        z.union([
            z.unknown(),
            z.string().datetime()
        ]),
        z.unknown()
    ]).optional(),
    status: z.enum([
        'CANCELLED',
        'COMPLETED',
        'FAILED',
        'PENDING',
        'RUNNING',
        'SCHEDULED'
    ]),
    submittedAt: z.string().datetime(),
    traceId: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    type: z.string(),
    wasmArtifactId: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional()
});

/**
 * Default Response
 */
export const zPostV2TasksArtifactsResponse = z.object({
    artifactId: z.string().optional()
});

export const zGetV2TasksArtifactsByIdPath = z.object({
    id: z.string()
});

/**
 * Default Response
 */
export const zGetV2TasksArtifactsByIdResponse = z.string();

export const zGetV2TasksByIdPath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zGetV2TasksByIdResponse = z.object({
    affinity: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    completedAt: z.union([
        z.union([
            z.unknown(),
            z.string().datetime()
        ]),
        z.unknown()
    ]).optional(),
    error: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    id: z.string().uuid(),
    image: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    metadata: z.record(z.unknown()).optional(),
    name: z.string(),
    nodeId: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    priority: z.string(),
    runtime: z.enum([
        'DOCKER',
        'NATIVE',
        'WASM'
    ]),
    specs: z.union([
        z.union([
            z.unknown(),
            z.object({
                cpuCores: z.number(),
                memoryGB: z.number()
            })
        ]),
        z.unknown()
    ]).optional(),
    startedAt: z.union([
        z.union([
            z.unknown(),
            z.string().datetime()
        ]),
        z.unknown()
    ]).optional(),
    status: z.enum([
        'CANCELLED',
        'COMPLETED',
        'FAILED',
        'PENDING',
        'RUNNING',
        'SCHEDULED'
    ]),
    submittedAt: z.string().datetime(),
    traceId: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional(),
    type: z.string(),
    wasmArtifactId: z.union([
        z.union([
            z.unknown(),
            z.string()
        ]),
        z.unknown()
    ]).optional()
});

export const zPostV2TasksByIdCancelPath = z.object({
    id: z.string().uuid()
});

export const zGetV2TasksByIdLogsPath = z.object({
    id: z.string().uuid()
});

export const zGetV2TasksByIdLogsQuery = z.object({
    level: z.string().optional(),
    limit: z.number().int().gte(1).lte(1000).optional()
});

export const zPostV2TasksByIdRetryPath = z.object({
    id: z.string().uuid()
});

export const zGetV2TasksByIdSchedulingDecisionPath = z.object({
    id: z.string().uuid()
});

export const zPostV2WebhooksBody = z.object({
    enabled: z.boolean().optional().default(true),
    events: z.array(z.string()).min(1),
    name: z.string().min(1).max(100).regex(/^[a-zA-Z0-9\s\-_]+$/),
    secret: z.string().min(32).max(128).optional(),
    url: z.string().url()
});

export const zPostV2WebhooksDeliveriesByIdRetryPath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zPostV2WebhooksDeliveriesByIdRetryResponse = z.object({
    message: z.string().optional(),
    success: z.boolean().optional()
});

/**
 * Default Response
 */
export const zGetV2WebhooksStatsResponse = z.object({
    active: z.number().optional(),
    avgLatency: z.number().optional(),
    failedLast24h: z.number().optional(),
    total: z.number().optional()
});

export const zDeleteV2WebhooksByIdPath = z.object({
    id: z.string().uuid()
});

export const zPatchV2WebhooksByIdBody = z.object({
    enabled: z.boolean().optional(),
    events: z.array(z.string()).min(1).optional(),
    name: z.string().min(1).max(100).optional(),
    secret: z.string().min(16).max(100).optional(),
    url: z.string().url().optional()
});

export const zPatchV2WebhooksByIdPath = z.object({
    id: z.string().uuid()
});

export const zGetV2WebhooksByIdDeliveriesPath = z.object({
    id: z.string().uuid()
});

export const zGetV2WebhooksByIdDeliveriesQuery = z.object({
    limit: z.number().int().gte(1).lte(100).optional()
});

export const zPostV2WebhooksByIdRedeliverByDeliveryIdPath = z.object({
    id: z.string().uuid(),
    deliveryId: z.string().uuid()
});

export const zPostV2WebhooksByIdTestPath = z.object({
    id: z.string().uuid()
});

/**
 * Default Response
 */
export const zPostV2WebhooksByIdTestResponse = z.object({
    deliveryId: z.string().optional(),
    success: z.boolean().optional()
});

export const zPostV2WorkflowsBody = z.object({
    edges: z.array(z.object({
        condition: z.string().optional(),
        from: z.string(),
        id: z.string(),
        to: z.string()
    })),
    name: z.string().min(1).max(200),
    nodes: z.array(z.object({
        config: z.record(z.unknown()),
        id: z.string().min(1).max(100).regex(/^[a-zA-Z0-9\-_]+$/),
        inputs: z.array(z.string()),
        name: z.string().min(1).max(100),
        outputs: z.array(z.string()),
        type: z.enum([
            'decision',
            'parallel',
            'subworkflow',
            'task',
            'wait'
        ])
    })).min(1),
    retryPolicy: z.object({
        initialDelay: z.number().int().gte(100).optional().default(1000),
        maxDelay: z.number().int().gte(1000).optional().default(60000),
        maxRetries: z.number().int().gte(0).lte(10).optional().default(3),
        multiplier: z.number().gte(1).optional().default(2)
    }).optional(),
    timeout: z.number().int().gte(1000).lte(86400000).optional().default(60000),
    variables: z.record(z.unknown()).optional(),
    version: z.string().regex(/^\d+\.\d+\.\d+$/)
});

export const zGetV2WorkflowsExecutionsByExecutionIdPath = z.object({
    executionId: z.string()
});

export const zGetV2WorkflowsByIdPath = z.object({
    id: z.string().uuid()
});

export const zPostV2WorkflowsByIdExecuteBody = z.object({
    input: z.record(z.unknown()).optional()
});

export const zPostV2WorkflowsByIdExecutePath = z.object({
    id: z.string().uuid()
});
