apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - statefulset-master.yaml
  - statefulset-replica.yaml
  - statefulset-sentinel.yaml
  - services.yaml
  - pdb.yaml
  - network-policy.yaml
